"""Type stubs for Ren'Py names our code uses.
Provides all top-level names that renpy/__init__.py dynamically exports
(via renpy.exports.*) but Pylance can't resolve from the TYPE_CHECKING block."""

from typing import Any, Callable, Optional, Union, Tuple, List

# Re-export submodules our code imports
from renpy import config as config
from renpy import display as display
from renpy import audio as audio
from renpy import text as text
from renpy import python as python
from renpy import loader as loader
from renpy import game as game
from renpy import exports as exports
from renpy import store as store

# Aliased at runtime by import_all() — no real renpy/music.py exists
from renpy.audio import music as music

# ---------------------------------------------------------------------------
# Top-level functions re-exported from renpy.exports
# ---------------------------------------------------------------------------

# Display / rendering
def render(widget: Any, width: int, height: int, st: float, at: float) -> Any: ...
class Render:
    def __init__(self, width: int, height: int) -> None: ...
    def blit(self, render: Any, pos: Tuple[int, int]) -> None: ...
    def canvas(self) -> Any: ...
    def get_size(self) -> Tuple[int, int]: ...
    def subsurface(self, rect: Tuple[int, int, int, int]) -> Any: ...
    def zoom(self, xzoom: float, yzoom: float) -> None: ...
    alpha: float

def displayable(name_or_displayable: Union[str, Any]) -> Any: ...
def image(name: Union[str, Tuple[str, ...]], d: Any = None) -> None: ...
def file(path: str) -> Any: ...
def loadable(path: str) -> bool: ...
def list_files() -> List[str]: ...

# Mouse / interaction
def get_mouse_pos() -> Tuple[int, int]: ...
def get_showing_tags(layer: str = "master") -> List[str]: ...
def showing(tag: str, layer: str = "master") -> bool: ...
def get_placed(name: str) -> Optional[Tuple[int, int, int, int]]: ...  # 8.x
def get_hovered() -> List[Any]: ...

# Screen management
def get_screen(name: str) -> Optional[Any]: ...
def show_screen(name: str, *args: Any, **kwargs: Any) -> None: ...
def hide_screen(name: str, layer: Optional[str] = None) -> None: ...
def restart_interaction() -> None: ...
def redraw(displayable: Any, delay: float) -> None: ...

# Focus
def focus_coordinates() -> Tuple[Optional[int], Optional[int], Optional[int], Optional[int]]: ...
def capture_focus(name: str) -> None: ...
def clear_capture_focus(name: str) -> None: ...
def get_focus_rect(name: str) -> Optional[Tuple[int, int, int, int]]: ...

# Misc
def pause(delay: float, music: Optional[Any] = None, with_none: Optional[Any] = None, hard: bool = False, predict: bool = False, checkpoint: bool = False) -> bool: ...
def invoke_in_new_context(callable: Callable[..., Any], *args: Any, **kwargs: Any) -> Any: ...
def register_sl_displayable(prefix: str, factory: Any) -> None: ...
def with_statement(trans: Any, always: bool = False, paired: Any = None, clear: bool = True, _with_none: bool = False) -> None: ...
def add_layer(layer: str, above: Optional[str] = None, below: Optional[str] = None, menu_clear: bool = True) -> None: ...

# Rollback
def in_rollback() -> bool: ...

# Replay (public :doc: replay export)
def call_replay(label: str, scope: Optional[dict] = None) -> None: ...

# Ren'Py version
version_tuple: Tuple[int, int, int, int]
version: str
version_only: str
version_name: str
