# Type stub for cue_lib.video.repeater
from typing import Any, Dict, List, Optional

from cue_lib._types import RepeaterOffset, VideoPoolDict
from cue_lib.marker_store import CueMarkerStore
from cue_lib.video.video import CueVideoManager
from cue_lib.state import CueContext
from cue_lib.markers import CueMarkerManager
from cue_lib.ui.dialogs import CueDialogBase

class CueMarkerRepeater(CueDialogBase):
    anchor: float
    anchor_text: str
    _store: CueMarkerStore
    _vid_manager: CueVideoManager
    _ctx: CueContext
    _markers: Optional[CueMarkerManager]
    _vid_key: str
    _pools_id: int
    _tracked: Optional[Dict[int, VideoPoolDict]]
    _anchor_pool: Optional[VideoPoolDict]
    _anchor_time: float
    offsets: List[RepeaterOffset]
    sel_count: int
    interval_text: str
    count_text: str
    dialog_visible: bool
    preview_sfx_enabled: bool
    is_fill_mode: bool

    def __init__(
        self,
        ctx: CueContext,
        store: CueMarkerStore,
        vid_manager: CueVideoManager,
        markers: Optional[CueMarkerManager] = None,
    ) -> None: ...
    def _sync_tracked(self) -> None: ...
    def _video_ctx(self) -> Any: ...
    def _offset_pool(self, offset: RepeaterOffset, time: float) -> VideoPoolDict: ...
    def _fill_count(self, interval: float) -> int: ...
    def _refill_count(self) -> None: ...
    def _shift_selected(self, delta: float) -> None: ...
    def open(self) -> None: ...
    def apply(self) -> None: ...
    def hide(self) -> None: ...
    def toggle_preview_sfx(self) -> None: ...
    def compute_preview_times(self) -> List[float]: ...
    def compute_preview_pools(self) -> List[VideoPoolDict]: ...
    def preview_text(self) -> str: ...
    def nudge_anchor(self, delta: float) -> None: ...
    def commit_anchor(self) -> None: ...
    def commit_interval(self) -> None: ...
    def nudge_interval(self, delta: float) -> None: ...
    def nudge_count(self, delta: int) -> None: ...
    def commit_count(self) -> None: ...
