# Type stub for cue_lib.video.repeater
from typing import Dict, List, Optional

from cue_lib._types import RepeaterOffset, VideoPoolDict

class CueMarkerRepeater:
    anchor: float
    anchor_text: str
    _vid_key: str
    _pools_id: int
    _tracked: Optional[Dict[int, VideoPoolDict]]
    _anchor_pool: Optional[VideoPoolDict]
    _anchor_time: float
    offsets: List[RepeaterOffset]
    sel_count: int
    interval_text: str
    count_text: str
    dialog_visible: bool
    preview_sfx_enabled: bool

    def __init__(self) -> None: ...
    def _sync_tracked(self) -> None: ...
    def _shift_selected(self, delta: float) -> None: ...
    def open(self) -> None: ...
    def apply(self) -> None: ...
    def hide(self) -> None: ...
    def toggle_preview_sfx(self) -> None: ...
    def compute_preview_times(self) -> List[float]: ...
    def compute_preview_pools(self) -> List[VideoPoolDict]: ...
    def preview_text(self) -> str: ...
    def nudge_anchor(self, delta: float) -> None: ...
    def commit_anchor(self) -> None: ...
    def commit_interval(self) -> None: ...
    def nudge_interval(self, delta: float) -> None: ...
    def nudge_count(self, delta: int) -> None: ...
    def commit_count(self) -> None: ...
