# Type stub for cue_lib.video.video
from typing import Final, List, Optional

from cue_lib.state import CueContext

CUE_SEEK_MIN_TARGET: Final = 0.001

def _cue_is_video_restart(prev_elapsed: float, curr_elapsed: float, duration: float) -> bool: ...

class CueVideoManager:
    channel: Optional[str]
    paused: bool
    refreshing: bool
    fps: int
    last_elapsed: float
    is_reset_pending: bool
    is_restart: bool
    sfx_breadcrumbs: List[float]

    def __init__(self, ctx: CueContext, channel: Optional[str] = None) -> None: ...
    def reset(self, channel: Optional[str] = None) -> None: ...
    def set_fps(self, fps: int) -> None: ...
    def reset_pause(self) -> None: ...
    def poll_restart(self) -> bool: ...
    def record_sfx_breadcrumb(self, frac: float) -> None: ...
    def clear_sfx_breadcrumbs(self) -> None: ...
    def get_elapsed(self) -> float: ...
    def get_duration(self) -> float: ...
    def get_video_path(self) -> Optional[str]: ...
    def toggle_pause(self) -> None: ...
    def seek_to(self, target_time: float) -> None: ...
    def poll_autopause(self) -> None: ...
    def sync_paused(self) -> None: ...
    def time_label(self) -> str: ...
    def frame_label(self) -> str: ...
