# Type stub for cue_lib.audio.tree.music_tree
from typing import Any, Dict, Final, List, Set, Tuple

from cue_lib._types import AudioSourceConfig
from cue_lib.audio.tree.file_tree import CueAudioTreeManager
from cue_lib.audio.tree.music_tree_rows import CueMusicTreeRows
from cue_lib.music.manager import CueMusicManager

CUE_GAME_MUSIC_DIRS: Final = ("music", "bgm", "ost", "soundtrack")

class CueMusicTree(CueAudioTreeManager):
    _music: CueMusicManager
    _rows: CueMusicTreeRows
    _reserved_labels: Tuple[str, ...]
    CUE_BUILTIN_SOURCES: Tuple[AudioSourceConfig, ...]
    user_files: List[str]
    game_files: List[str]
    user_tree: List[Dict[str, Any]]
    game_tree: List[Dict[str, Any]]
    user_scan_error: str
    game_scan_error: str
    external_folders: List[str]
    external_files: List[str]
    external_sources: List[Dict[str, Any]]

    def __init__(self, music: CueMusicManager) -> None: ...
    def scan(self) -> None: ...
    def _discover_user(self, results_set: Set[str]) -> None: ...
    def _discover_game(self, results_set: Set[str]) -> None: ...
    def _merged_tree(self) -> List[Dict[str, Any]]: ...
    def add_song_to_trigger(self, ref: str, record: bool = True) -> None: ...
    def add_folder_to_trigger(self, ref: str, record: bool = True) -> None: ...
    def ref_from_display(self, display_path: str) -> str: ...
    def display_for_ref(self, ref: str) -> str: ...
    def preview(self, ref: str, volume: float = 1.0) -> None: ...
    def tree_rows(self, *state: object) -> List[Dict[str, Any]]: ...
    def content_rows(
        self, search_query: str, preset_names: List[str], current_file: object
    ) -> List[Dict[str, Any]]: ...
