# Type stub for cue_lib.audio.tree.music_tree_rows
from typing import Any, Dict, List

from cue_lib.audio.tree.tree_rows import CueTreeRowsBuilder

def _cue_preview_music_preset(preset_name: str) -> None: ...

class CueMusicTreeRows(CueTreeRowsBuilder):
    def row_buttons(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, item: Dict[str, Any], current_file: object
    ) -> List[Dict[str, Any]]: ...
    def _recent_rows(self, entries: List[Dict[str, str]], current_file: object) -> List[Dict[str, Any]]: ...
    def _preset_rows(self, preset_names: List[str]) -> List[Dict[str, Any]]: ...
    def _preset_children(self, preset_names: List[str]) -> List[Dict[str, Any]]: ...
    def content_rows(
        self, search_query: str, preset_names: List[str], current_file: object
    ) -> List[Dict[str, Any]]: ...
