# Type stub for cue_lib.audio.tree.sfx_tree
from typing import Any, Dict, List, Optional, Set, Tuple

from cue_lib._types import AudioSourceConfig, TreeRowDict
from cue_lib.audio.cue_sfx_pack import CueSfxPackDownloader
from cue_lib.audio.sfx_manager import CueSfxManager
from cue_lib.audio.tree.file_tree import CueAudioTreeManager
from cue_lib.audio.tree.sfx_tree_rows import CueSfxTreeRows
from cue_lib.db import CueDatabase
from cue_lib.intensity import CueIntensityManager
from cue_lib.paths import CuePaths

class CueSfxLibraryTree(CueAudioTreeManager):
    external_folders: List[str]
    builtin_files: List[str]
    builtin_tree: List[Dict[str, Any]]
    builtin_scan_error: str
    external_files: List[str]
    external_sources: List[Dict[str, Any]]
    expanded_file_refs: Dict[str, bool]
    presets_expanded: bool
    expanded_presets: Dict[str, bool]
    video_presets_expanded: bool
    expanded_video_presets: Dict[str, bool]
    expanded_video_pools: Dict[str, Dict[int, bool]]
    disabled_files: Set[str]
    is_sidebar_mode: bool
    sidebar_width: int
    igroups_expanded: bool
    expanded_igroups: Dict[str, bool]
    ilevel_add_target: Optional[Tuple[str, int]]
    expanded_ilevels: Dict[str, Set[int]]
    _intensity: Optional[CueIntensityManager]
    add_to_pool_warning: str
    _sfx: CueSfxManager
    _rows: CueSfxTreeRows
    _reserved_labels: Tuple[str, ...]
    sfx_pack: CueSfxPackDownloader
    CUE_BUILTIN_SOURCES: Tuple[AudioSourceConfig, ...]

    def __init__(self, paths: CuePaths, db: CueDatabase) -> None: ...
    def scan(self) -> None: ...
    def ref_from_display(self, display_path: str) -> str: ...
    def display_for_ref(self, ref: str) -> str: ...
    def resolve_path(self, ref: str) -> str: ...
    def _merged_tree(self) -> List[Dict[str, Any]]: ...
    def toggle_file_enabled(self, full_path: str) -> None: ...
    def toggle_file_ref_expand(self, folder_ref: str) -> None: ...
    def toggle_presets_expand(self) -> None: ...
    def toggle_preset_expand(self, preset_name: str) -> None: ...
    def toggle_video_presets_expand(self) -> None: ...
    def toggle_video_preset_expand(self, preset_name: str) -> None: ...
    def toggle_video_pool_expand(self, preset_name: str, pool_index: int) -> None: ...
    def toggle_igroups_expand(self) -> None: ...
    def toggle_igroup_expand(self, group_name: str) -> None: ...
    def add_level(self, group_name: str) -> None: ...
    def toggle_ilevel_add_mode(self, group_name: str, ilevel_id: int) -> None: ...
    def toggle_ilevel_expand(self, group_name: str, ilevel_id: int) -> None: ...
    def _ilevel_target_valid(self, group_name: str, ilevel_id: int) -> bool: ...
    def ilevel_add_file(self, group_name: str, ilevel_id: int, file_ref: str) -> None: ...
    def ilevel_add_folder(self, group_name: str, ilevel_id: int, folder_path: str) -> None: ...
    def level_has_file(self, group_name: str, ilevel_id: int, file_ref: str) -> bool: ...
    def tree_rows(self, *state: object) -> List[TreeRowDict]: ...
    def content_rows(
        self,
        search_query: str,
        preset_names: List[str],
        video_preset_names: List[str],
        igroup_names: List[str],
        is_video: bool,
        tgt_ok: bool,
        unplayable: Dict[str, str],
    ) -> List[TreeRowDict]: ...
    def set_add_to_pool_warning(self, message: str) -> None: ...
    def clear_add_to_pool_warning(self) -> None: ...
    def toggle_sidebar_mode(self) -> None: ...
    def persist_sidebar_state(self) -> None: ...
    def set_sidebar_width(self, width: int) -> None: ...
    def _encode_ui_state(self) -> Dict[str, Any]: ...
    def save_ui_state(self) -> None: ...
    def _apply_ui_state(self, blob: Optional[Dict[str, Any]]) -> None: ...
    def restore_ui_state(self) -> None: ...
