from typing import Any, Callable, Dict, List, Optional, Tuple

from cue_lib._types import MarkerEntry
from cue_lib.db import CueDatabase

def _level_ramp(count: int, max_value: float) -> List[float]: ...
def _cue_intensity_volume_mult(level_mult: float) -> float: ...

class CueIntensityFlags:
    enabled: bool
    sfx_levels: bool
    volume: bool
    frequency: bool

    def __init__(
        self,
        enabled: bool = True,
        sfx_levels: bool = True,
        volume: bool = True,
        frequency: bool = True) -> None: ...

class CueIntensityResolution:
    group: str
    level: int
    folder: Optional[str]
    volume_mult: float
    freq_mult: float
    files: List[str]

    def __init__(
        self,
        group: str,
        level: int,
        folder: Optional[str],
        volume_mult: float,
        freq_mult: float,
        files: Optional[List[str]] = None) -> None: ...

class CueIntensityManager:
    def __init__(self, db: CueDatabase) -> None: ...
    def list_igroups(self) -> List[str]: ...
    def get_igroup(self, name: str) -> Optional[Dict[str, Any]]: ...
    def create_igroup(self, name: str) -> Optional[str]: ...
    def rename_igroup(self, old_name: str, new_name: str) -> Optional[str]: ...
    def delete_igroup(self, name: str) -> None: ...
    def add_folder(self, name: str, folder_path: str) -> Optional[str]: ...
    def remove_level(self, name: str, index: int) -> None: ...
    def move_level(self, name: str, index: int, delta: int) -> None: ...
    def resolve_hook(self, files: Optional[List[str]]) -> Optional[Tuple[str, int]]: ...
    def group_for_folder(self, folder: str) -> Optional[str]: ...
    def pool_group(self, files: Optional[List[str]]) -> Optional[str]: ...
    def check_add_folder(self, pool_files: Optional[List[str]], folder: str) -> Optional[str]: ...
    def flags_from_entry(self, entry: Optional[MarkerEntry]) -> CueIntensityFlags: ...
    def level_folder(self, name: str, level: int) -> Optional[str]: ...
    def level_multipliers(self, name: str, level: int) -> Tuple[float, float]: ...
    def resolve_pool_intensity(
        self,
        files: Optional[List[str]],
        current_speed: float,
        variants: Optional[List[float]],
        is_populated: Optional[Callable[[str], bool]] = None,
        flags: Optional[CueIntensityFlags] = None) -> Optional[CueIntensityResolution]: ...
    def resolve_video_intensity(
        self,
        pools_files: List[List[str]],
        current_speed: float,
        variants: Optional[List[float]],
        is_populated: Optional[Callable[[str], bool]] = None,
        flags: Optional[CueIntensityFlags] = None) -> Optional[CueIntensityResolution]: ...
    def current_level(
        self,
        pools_files: List[List[str]],
        current_speed: float,
        variants: Optional[List[float]],
        flags: Optional[CueIntensityFlags] = None) -> Optional[Tuple[int, int]]: ...
    def video_hook(self, pools_files: List[List[str]]) -> Optional[str]: ...
    def is_pool_intensity_active(
        self,
        files: Optional[List[str]],
        variants: Optional[List[float]],
        flags: Optional[CueIntensityFlags] = None) -> bool: ...
    def variant_levels(self, group_name: str, variants: List[float]) -> Optional[List[Tuple[float, int]]]: ...
