from typing import Any, Callable, Dict, List, Optional, Tuple

from cue_lib._types import MarkerEntry
from cue_lib.db import CueDatabase

def _level_ramp(count: int, max_value: float) -> List[float]: ...
def _cue_intensity_volume_mult(level_mult: float) -> float: ...

class CueIntensityFlags:
    enabled: bool
    sfx_levels: bool
    volume: bool
    frequency: bool

    def __init__(
        self, enabled: bool = True, sfx_levels: bool = True, volume: bool = True, frequency: bool = True
    ) -> None: ...

class CueIntensityResolution:
    group: str
    level: int
    volume_mult: float
    freq_mult: float
    files: List[str]

    def __init__(
        self, group: str, level: int, volume_mult: float, freq_mult: float, files: Optional[List[str]] = None
    ) -> None: ...

class CueIntensityManager:
    def __init__(self, db: CueDatabase) -> None: ...
    def _load(self) -> Dict[str, Any]: ...
    def list_igroups(self) -> List[str]: ...
    def get_igroup(self, name: str) -> Optional[Dict[str, Any]]: ...
    def create_igroup(self, name: str) -> Optional[str]: ...
    def delete_igroup(self, name: str) -> None: ...
    def add_level(self, name: str) -> Optional[int]: ...
    def add_level_file(self, name: str, ilevel_id: int, file_ref: str) -> Optional[str]: ...
    def remove_level_file(self, name: str, ilevel_id: int, file_ref: str) -> None: ...
    def remove_level(self, name: str, index: int) -> None: ...
    def move_level(self, name: str, index: int, delta: int) -> None: ...
    def level_files(self, name: str, level_index: int) -> Optional[List[str]]: ...
    def level_files_by_id(self, name: str, ilevel_id: int) -> Optional[List[str]]: ...
    def level_multipliers(self, name: str, level_index: int) -> Tuple[float, float]: ...
    def flags_from_entry(self, entry: Optional[MarkerEntry]) -> CueIntensityFlags: ...
    def resolve_pool_intensity(
        self,
        igroup: Optional[str],
        ilevel_id: Optional[int],
        current_speed: float,
        variants: Optional[List[float]],
        flags: Optional[CueIntensityFlags] = None,
        resolve_files: Optional[Callable[[List[str]], List[str]]] = None,
    ) -> Optional[CueIntensityResolution]: ...
    def resolve_video_intensity(
        self,
        pool_hooks: List[Tuple[Optional[str], Optional[int]]],
        current_speed: float,
        variants: Optional[List[float]],
        flags: Optional[CueIntensityFlags] = None,
        resolve_files: Optional[Callable[[List[str]], List[str]]] = None,
    ) -> Optional[CueIntensityResolution]: ...
    def current_level(
        self,
        pool_hooks: List[Tuple[Optional[str], Optional[int]]],
        current_speed: float,
        variants: Optional[List[float]],
        flags: Optional[CueIntensityFlags] = None,
    ) -> Optional[Tuple[int, int]]: ...
    def video_hook(self, pool_hooks: List[Tuple[Optional[str], Optional[int]]]) -> Optional[str]: ...
    def is_pool_intensity_active(
        self, igroup: Optional[str], variants: Optional[List[float]], flags: Optional[CueIntensityFlags] = None
    ) -> bool: ...
    def variant_levels(self, group_name: str, variants: List[float]) -> Optional[List[Tuple[float, int]]]: ...
