# Type stub for cue_lib.beat
from typing import Any, Dict, List

class CueBeatManager:
    anchor: float
    offsets: List[Dict[str, Any]]
    sel_count: int
    interval_text: str
    count_text: str
    dialog_visible: bool
    preview_sfx_enabled: bool

    def __init__(self) -> None: ...
    def open(self) -> None: ...
    def apply(self) -> None: ...
    def hide(self) -> None: ...
    def toggle_preview_sfx(self) -> None: ...
    def compute_preview_times(self) -> List[float]: ...
    def compute_preview_pools(self) -> List[Dict[str, Any]]: ...
    def preview_text(self) -> str: ...
    def commit_interval(self) -> None: ...
    def nudge_interval(self, delta: float) -> None: ...
    def nudge_count(self, delta: int) -> None: ...
    def commit_count(self) -> None: ...
