# Type stub for cue_lib.displayables
from typing import Any, Callable, List, Optional, Tuple
from renpy.display.core import Displayable

class SelfUpdatingLabel(Displayable):
    def __init__(self, getter: Callable[[], str], style: str = "default", interval: float = 0.05, **properties: Any) -> None: ...
    def render(self, width: int, height: int, st: float, at: float) -> Any: ...

class VideoTimeline(Displayable):
    BAR_H: int
    def __init__(self, interval: float = 0.016, **properties: Any) -> None: ...
    def render(self, width: int, height: int, st: float, at: float) -> Any: ...
    def event(self, ev: Any, x: int, y: int, st: float) -> Optional[Any]: ...

class CueVideoMarkerTimeline(Displayable):
    TRACK_H: int
    TAB_H: int
    LINE_H: int
    TAB_W: int
    DRAG_THRESH: int
    PAD_X: int
    SEL_BG: str
    SEL_LINE: str

    def __init__(self, get_markers: Callable[[], List[Any]], get_active: Callable[[], int], set_active: Callable[[int], None], set_time: Callable[[int, float], None], get_dur: Callable[[], float], **kw: Any) -> None: ...
    def render(self, width: int, height: int, st: float, at: float) -> Any: ...
    def event(self, ev: Any, x: int, y: int, st: float) -> Optional[Any]: ...

class _Tooltip(Displayable):
    def __init__(self, text: str, **properties: Any) -> None: ...
    def render(self, width: int, height: int, st: float, at: float) -> Any: ...

class _MarkerTooltipOverlay(Displayable):
    def __init__(self, **properties: Any) -> None: ...
    def render(self, width: int, height: int, st: float, at: float) -> Any: ...
