# Type stub for cue_lib.ffmpeg
from typing import Dict, List, Optional, Set, Tuple

CREATIONFLAGS: int

class CueFFmpeg:
    VIDEO_ENCODERS: Dict[str, List[str]]
    AUDIO_ENCODERS: Dict[str, List[str]]

    def __init__(self) -> None: ...
    def ffmpeg_available(self) -> bool: ...
    def ffprobe_available(self) -> bool: ...
    def load_encoders(self) -> None: ...
    def pick_encoder(self, codec_name: str, category: str) -> Optional[str]: ...
    def probe_codecs(self, fspath: str) -> Tuple[str, str]: ...
    def probe_has_audio(self, fspath: str) -> bool: ...
    def probe_fps(self, fspath: str) -> int: ...
    def probe_bitrate(self, fspath: str) -> Optional[str]: ...

    @staticmethod
    def build_atempo(speed: float) -> List[str]: ...

    def build_ffmpeg_cmds(
        self,
        fspath: str,
        temp_path: str,
        speed: float,
        vcodec: str,
        acodec: str,
        has_audio: bool,
        target_bitrate: Optional[str],
        interpolate: bool = False,
        source_fps: int = 30,
        fast: bool = False,
    ) -> Tuple[List[List[str]], Optional[str]]: ...
