# Type stub for cue_lib.markers
from typing import Any, Dict, List, Optional, Set, Tuple

class ResolvedPool:
    files: List[str]
    volume: float
    frequency: int
    trigger_on_shake: bool
    exclusive: bool
    def __init__(self, files: List[str], volume: float, frequency: int, trigger_on_shake: bool, exclusive: bool = False) -> None: ...

class CueMarkerContext:
    def __init__(self, manager: Any) -> None: ...
    def add_file(self, file_index: int) -> None: ...
    def remove_file(self, pool_index: int, file_index: int) -> None: ...
    def clear(self) -> None: ...
    def add_pool(self) -> None: ...
    def remove_pool(self, pool_index: int) -> None: ...
    def get_active(self) -> int: ...
    def set_active(self, pool_index: int) -> None: ...
    def apply_preset(self, preset_name: str) -> None: ...
    def add_folder(self, folder_path: str) -> None: ...

class CueImageContext(CueMarkerContext): ...
class CueDialogueContext(CueMarkerContext): ...

class CueVideoContext(CueMarkerContext):
    target_pool: int
    selected: Set[int]
    edit_text: str

    def __init__(self, manager: Any) -> None: ...
    def add_file(self, file_index: int) -> None: ...
    def add_folder(self, folder_path: str) -> None: ...
    def add_pool(self) -> None: ...
    def apply_preset(self, preset_name: str) -> None: ...
    def clear(self) -> None: ...
    def commit_text(self) -> None: ...
    def duplicate_pool(self, ts_index: int) -> None: ...
    def finalize_drag(self) -> None: ...
    def get_delete_message(self) -> str: ...
    def get_duration(self) -> float: ...
    def get_markers(self) -> List[Dict[str, Any]]: ...
    def get_selected(self) -> Set[int]: ...
    def has_markers(self) -> bool: ...
    def nudge(self, delta: float) -> None: ...
    def remove_file(self, ts_index: int, file_index: int) -> None: ...
    def remove_pool(self, ts_index: int) -> None: ...
    def remove_selected(self) -> None: ...
    def select_tab(self, pool_index: int) -> None: ...
    def set_active(self, pool_index: int) -> None: ...
    def set_time(self, idx: int, new_time: float) -> None: ...
    def sync_text(self) -> None: ...

class CueLoopContext(CueMarkerContext):
    def __init__(self, manager: Any) -> None: ...
    def add_pool(self) -> None: ...
    def clear(self) -> None: ...
    def set_frequency(self, freq: int) -> None: ...
    def set_exclusive(self, value: bool) -> None: ...

    @staticmethod
    def get_delay(frequency: int = 1) -> float: ...

class CueMarkerManager:
    image: CueImageContext
    dialogue: CueDialogueContext
    video: CueVideoContext
    loop: CueLoopContext
    clipboard: Optional[Dict[str, Any]]

    def __init__(self) -> None: ...
    def get(self, key: str, default: Any = None) -> Optional[Dict[str, Any]]: ...
    def setdefault(self, key: str, default: Any) -> Any: ...
    def pop(self, key: str, *args: Any) -> Any: ...
    def items(self) -> Any: ...
    def keys(self) -> Any: ...

    def create_preset(self, name: str, pool_dict: Dict[str, Any]) -> None: ...
    def delete_preset(self, name: str) -> None: ...
    def preset_remove_file(self, name: str, file_path: str) -> None: ...
    def get_preset(self, name: str) -> Optional[Dict[str, Any]]: ...
    def list_presets(self) -> List[str]: ...

    def create_video_preset(self, name: str, entry: Dict[str, Any]) -> None: ...
    def delete_video_preset(self, name: str) -> None: ...
    def get_video_preset(self, name: str) -> Optional[Dict[str, Any]]: ...
    def list_video_presets(self) -> List[str]: ...
    def video_preset_out_of_range(self, name: str) -> int: ...
    def apply_video_preset(self, name: str) -> None: ...

    def resolve_pool(self, pool: Dict[str, Any]) -> ResolvedPool: ...

    def save_persistent(self) -> None: ...
    def load_persistent(self) -> None: ...
    def backup_to_file(self) -> None: ...
    def restore_from_file(self) -> None: ...

    def copy_context(self) -> None: ...
    def paste_context(self) -> None: ...
