# Type stub for cue_lib.ui_logic
from typing import Any, Optional, Callable

class CuePresetDialog:
    trigger_key: Optional[str]
    pool_idx: int
    name: str

    def __init__(self) -> None: ...
    def open(self, trigger_key: str, pool_idx: int) -> None: ...
    def commit(self) -> None: ...
    def cancel(self) -> None: ...

class CueVideoPresetDialog:
    name: str

    def __init__(self) -> None: ...
    def open(self) -> None: ...
    def commit(self) -> None: ...
    def cancel(self) -> None: ...

class CueConfirmDialog:
    message: str
    on_confirm: Optional[Callable[..., Any]]

    def __init__(self) -> None: ...
    def show(self, message: str, confirm_action: Any) -> None: ...
    def hide(self) -> None: ...

def _cue_confirm_delete_preset(preset_name: str) -> None: ...
def _cue_confirm_delete_video_preset(preset_name: str) -> None: ...
def _cue_maybe_apply_video_preset(preset_name: str) -> None: ...
def _cue_preview_video_preset(preset_name: str) -> None: ...
def _cue_detach_active_video_ts(*args: Any) -> None: ...
def _cue_detach_pool_at(trigger_key: str, pool_index: int) -> None: ...
def _cue_make_tab_action(fn: Any, args_tuple: tuple, pi: int) -> Any: ...
def _cue_count_file_list_rows(folder_label: Optional[str], folder_children: Any, files: list) -> int: ...
