# Type stub for cue_lib.ui.dialogs
from typing import Any, Callable, List, Optional

from cue_lib._types import MarkerEntry  # pyright: ignore[reportUnusedImport]

class CueDialogBase:
    id: str

    def __init__(self, dialog_id: str) -> None: ...
    def _show(self) -> None: ...
    def _hide(self) -> None: ...

class CueDialogs:
    preset: CuePresetDialog
    music_preset: CueMusicPresetDialog
    video_preset: CueVideoPresetDialog
    confirm: CueConfirmDialog
    merge: CueMergeDialog
    intensity: CueIntensityGroupDialog
    active_id: Optional[str]

    def __init__(self) -> None: ...
    def show(self, dialog_id: str) -> None: ...
    def hide(self) -> None: ...

class CuePresetDialog(CueDialogBase):
    marker_key: Optional[str]
    pool_idx: int
    name: str

    def __init__(self) -> None: ...
    def open(self, marker_key: str, pool_idx: int) -> None: ...
    def commit(self) -> None: ...
    def cancel(self) -> None: ...
    def _reset(self) -> None: ...

class CueMusicPresetDialog(CueDialogBase):
    music_key: Optional[str]
    songs: List[str]
    name: str

    def __init__(self) -> None: ...
    def open(self, music_key: str) -> None: ...
    def commit(self) -> None: ...
    def cancel(self) -> None: ...
    def _reset(self) -> None: ...

class CueVideoPresetDialog(CueDialogBase):
    name: str

    def __init__(self) -> None: ...
    def open(self) -> None: ...
    def commit(self) -> None: ...
    def cancel(self) -> None: ...

class CueIntensityGroupDialog(CueDialogBase):
    name: str
    renaming: Optional[str]
    error: str

    def __init__(self) -> None: ...
    def open(self) -> None: ...
    def open_rename(self, group_name: str) -> None: ...
    def commit(self) -> None: ...
    def cancel(self) -> None: ...
    def _reset(self) -> None: ...

class CueConfirmDialog(CueDialogBase):
    message: str
    on_confirm: Optional[Callable[..., None]]

    def __init__(self) -> None: ...
    def show(self, message: str, confirm_action: Callable[..., None]) -> None: ...
    def show_or_run(self, message: str, confirm_action: Callable[..., None]) -> None: ...
    def hide(self) -> None: ...

class CueMergeDialog(CueDialogBase):
    imp: Optional[str]
    checked: dict
    counts: dict
    overwrites: List[str]
    total_files: int
    error: str

    def __init__(self, imports: Any) -> None: ...
    def open(self, imp: str) -> None: ...
    def toggle(self, cat: int) -> None: ...
    def is_checked(self, cat: int) -> bool: ...
    def is_category_enabled(self, cat: int) -> bool: ...
    def summary(self) -> str: ...
    def cancel(self) -> None: ...
    def confirm(self) -> None: ...
    def _reset(self) -> None: ...

def _cue_confirm_delete_preset(preset_name: str) -> None: ...
def _cue_confirm_delete_video_preset(preset_name: str) -> None: ...
def _cue_confirm_delete_music_preset(preset_name: str) -> None: ...
def _cue_confirm_delete_igroup(igroup_name: str) -> None: ...
def _cue_maybe_apply_video_preset(preset_name: str) -> None: ...
