# Type stub for cue_lib.ui.focus
from typing import Any, Optional

def _cue_install_focus_pin() -> None: ...
def _cue_action_manages_input(action: Any) -> bool: ...
def _cue_field_control(f: Any) -> bool: ...
def _cue_focusable_at_point(x: Any, y: Any, keep: Optional[Any] = None) -> Optional[Any]: ...
