# Type stub for cue_lib.ui.overlay
from typing import Dict, Optional, Tuple

from cue_lib.ui.components.select.select import CueSelect

class CueOverlay:
    is_visible: bool
    active_page: int
    collapsed_sections: Dict[str, bool]
    active_input: str
    # The focus pin captures rects as floats; select.open() int()s them before
    # anchoring the dropdown (screen xpos treats floats as parent fractions).
    active_input_rect: Optional[Tuple[float, float, float, float]]
    active_dropdown: Optional[CueSelect]

    def toggle(self) -> None: ...
    def set_page(self, page: int) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def _clear_active_input(self) -> None: ...
    def _close_active_dropdown(self) -> None: ...
    def toggle_section(self, section_name: str) -> None: ...
    def _save_collapsed_sections(self) -> None: ...
    def _load_collapsed_sections(self) -> None: ...
