# Type stub for cue_lib.ui.overlay
from typing import Dict

class CueOverlay:
    is_visible: bool
    active_page: int
    collapsed_sections: Dict[str, bool]

    def toggle(self) -> None: ...
    def set_page(self, page: int) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def toggle_section(self, section_name: str) -> None: ...
    def _save_collapsed_sections(self) -> None: ...
    def _load_collapsed_sections(self) -> None: ...
