# Type stub for cue_lib.audio.audio_tree
from typing import Any, Dict, List, Set

class CueAudioTreeManager:
    files: List[str]
    tree: List[Dict[str, Any]]
    scan_error: str
    visible_tree: List[Dict[str, Any]]
    expanded_folders: Dict[str, bool]
    search_query: str

    def __init__(self) -> None: ...
    def scan(self) -> None: ...
    def _discover(self, results_set: Set[str]) -> None: ...
    def _discover_walk_dir(self, results_set: Set[str], search_path: str) -> None: ...
    def rebuild_tree(self) -> None: ...
    def clear_search(self) -> None: ...
    def _walk_tree(
        self,
        items: List[Dict[str, Any]],
        prefix: str,
        depth: int,
        result: List[Dict[str, Any]],
        force_expand: bool = ...) -> None: ...
    def _file_node(self, item: Dict[str, Any], full: str, depth: int) -> Dict[str, Any]: ...
    def toggle_folder(self, folder_path: str) -> None: ...
