# Type stub for cue_lib.audio.file_tree
from typing import Any, Dict, List, Optional, Set, Tuple

from cue_lib.audio.recent import CueRecentManager

CUE_SEARCH_MAX_ROWS: int

class CueAudioTreeManager:
    external_folders: List[str]
    external_files: List[str]
    external_sources: List[Dict[str, Any]]
    files: List[str]
    _file_index: Dict[str, int]
    tree: List[Dict[str, Any]]
    scan_error: str
    visible_tree: List[Dict[str, Any]]
    expanded_folders: Dict[str, bool]
    search_query: str
    search_truncated: int
    _search_applied: str
    _has_expanded_roots: bool
    _recent: Optional[CueRecentManager]
    _persist_key: Optional[str]
    _reserved_labels: Tuple[str, ...]

    def __init__(self) -> None: ...
    def scan(self) -> None: ...
    def _discover(self, results_set: Set[str]) -> None: ...
    def _discover_walk_dir(self, results_set: Set[str], search_path: str) -> None: ...
    def _scan_external(self) -> None: ...
    def _scan_external_root(self, abs_root: str, used_labels: List[str]) -> Dict[str, Any]: ...
    def _external_label(self, abs_root: str, used_labels: List[str]) -> str: ...
    def _expand_roots(self) -> None: ...
    def rebuild_tree(self) -> None: ...
    def clear_search(self) -> None: ...
    def maybe_rebuild(self) -> None: ...
    def _walk_tree(
        self,
        items: List[Dict[str, Any]],
        prefix: str,
        depth: int,
        result: List[Dict[str, Any]],
        force_expand: bool = ...,
        abs_root: Optional[str] = ...,
    ) -> None: ...
    def _file_node(self, item: Dict[str, Any], full: str, depth: int) -> Dict[str, Any]: ...
    def _merged_tree(self) -> List[Dict[str, Any]]: ...
    def _rebuild_merged(self) -> None: ...
    def _append_external_sources(self, result: List[Dict[str, Any]]) -> None: ...
    def _external_payload_for_display(self, display_path: str) -> Optional[str]: ...
    def toggle_folder(self, folder_path: str) -> None: ...
    def _save_expansion(self) -> None: ...
    def _restore_expansion(self) -> None: ...
