# Type stub for cue_lib.audio.music_tree
from typing import Any, Dict, List

from cue_lib.audio.audio_tree import CueAudioTreeManager
from cue_lib.audio.game_music import CueGameMusic
from cue_lib.audio.music import CueMusicManager
from cue_lib.audio.tree_rows import CueMusicTreeRows
from cue_lib.audio.user_music import CueUserMusic

class CueCombinedMusicTree(CueAudioTreeManager):
    _music: CueMusicManager
    user_music: CueUserMusic
    game_music: CueGameMusic
    _user_tree_id: object
    _game_tree_id: object
    _rows: CueMusicTreeRows

    def __init__(self, music: CueMusicManager, user_music: CueUserMusic, game_music: CueGameMusic) -> None: ...
    def rebuild_tree(self) -> None: ...
    def _merged_tree(self) -> List[Dict[str, Any]]: ...
    def maybe_rebuild(self) -> None: ...
    def add_song_to_trigger(self, display_path: str, record: bool = True) -> None: ...
    def add_folder_to_trigger(self, display_path: str, record: bool = True) -> None: ...
    def ref_display_path(self, ref: str) -> str: ...
    def preview(self, display_path: str, volume: float = 1.0) -> None: ...
    def tree_rows(self, *state: object) -> List[Dict[str, Any]]: ...
