# Type stub for cue_lib.audio.recent
from typing import Callable, List


class CueRecentManager:
    key: str
    _keep: Callable[[str, str], bool]
    _entries: List[dict]
    expanded: bool

    def __init__(self, key: str, keep: Callable[[str, str], bool]) -> None: ...
    def load(self) -> None: ...
    def save(self) -> None: ...
    def record(self, kind: str, ref: str) -> None: ...
    def entries(self) -> List[dict]: ...
    def has_entries(self) -> bool: ...
    def toggle(self) -> None: ...
    def on_search_clear(self) -> None: ...
    def prune(self) -> None: ...


def _cue_keep_sfx(kind: str, ref: str, sfx_files: list, preset_names: list) -> bool: ...
