# Type stub for cue_lib.audio.recent
from typing import Callable, Final, List

from cue_lib.audio.user_music import CueUserMusic
from cue_lib.audio.game_music import CueGameMusic

CUE_RECENT_MAX_ENTRIES: Final = 8


class CueRecentManager:
    key: str
    _keep: Callable[[str, str], bool]
    _entries: List[dict]
    expanded: bool

    def __init__(self, key: str, keep: Callable[[str, str], bool]) -> None: ...
    def load(self) -> None: ...
    def save(self) -> None: ...
    def record(self, kind: str, ref: str) -> None: ...
    def entries(self) -> List[dict]: ...
    def has_entries(self) -> bool: ...
    def toggle(self) -> None: ...
    def prune(self) -> None: ...


def _cue_keep_sfx(kind: str, ref: str, sfx_files: list, preset_names: list) -> bool: ...
def _cue_music_ref_tag(ref: str) -> tuple: ...
def _cue_keep_music(kind: str, ref: str, user_music: CueUserMusic, game_music: CueGameMusic) -> bool: ...
