# Type stub for cue_lib.audio.sfx_manager
from typing import Dict, List, Optional, Set

from cue_lib._types import AudioTreeNode

class CueSfxManager:
    files: List[str]
    audio_tree: List[AudioTreeNode]
    scan_error: str
    visible_tree: List[AudioTreeNode]
    expanded_folders: Dict[str, bool]
    expanded_file_refs: Dict[str, bool]
    presets_expanded: bool
    expanded_presets: Dict[str, bool]
    video_presets_expanded: bool
    expanded_video_presets: Dict[str, bool]
    disabled_files: Set[str]

    def __init__(self) -> None: ...
    def scan(self) -> None: ...
    def rebuild_tree(self) -> None: ...
    def toggle_folder(self, folder_path: str) -> None: ...
    def toggle_file_enabled(self, full_path: str) -> None: ...
    def toggle_file_ref_expand(self, folder_ref: str) -> None: ...
    def count_file_list_rows(
        self,
        folder_label: Optional[str],
        folder_children: Optional[List[str]],
        files: List[str]) -> int: ...
    def toggle_presets_expand(self) -> None: ...
    def toggle_preset_expand(self, preset_name: str) -> None: ...
    def toggle_video_presets_expand(self) -> None: ...
    def toggle_video_preset_expand(self, preset_name: str) -> None: ...
