# Type stub for cue_lib.audio.sfx_manager
from typing import Any, Dict, List, Optional, Set, Tuple

from cue_lib.audio.file_tree import CueAudioTreeManager
from cue_lib.audio.file_tree_rows import CueSfxTreeRows
from cue_lib.audio.wav_playable import CueWavPlayable
from cue_lib.db import CueDatabase
from cue_lib.markers import CueMarkerManager
from cue_lib.paths import CuePaths
from cue_lib.intensity import CueIntensityManager
from cue_lib.state import CueContext
from cue_lib.volume import CueVolumeManager
from cue_lib._types import MarkerEntry, PoolDict

def _cue_sfx_channel_name(index: int) -> str: ...
def _cue_sfx_channel_index(ch_name: str) -> int: ...

class CueSfxLibraryTree(CueAudioTreeManager):
    external_folders: List[str]
    builtin_files: List[str]
    builtin_tree: List[Dict[str, Any]]
    builtin_scan_error: str
    external_files: List[str]
    external_sources: List[Dict[str, Any]]
    expanded_file_refs: Dict[str, bool]
    presets_expanded: bool
    expanded_presets: Dict[str, bool]
    video_presets_expanded: bool
    expanded_video_presets: Dict[str, bool]
    expanded_video_pools: Dict[str, Dict[int, bool]]
    disabled_files: Set[str]
    is_sidebar_mode: bool
    sidebar_width: int
    igroups_expanded: bool
    expanded_igroups: Dict[str, bool]
    ilevel_add_target: Optional[Tuple[str, int]]
    expanded_ilevels: Dict[str, Set[int]]
    _intensity: Optional[CueIntensityManager]
    add_to_pool_warning: str
    _sfx: CueSfxManager
    _rows: CueSfxTreeRows

    def __init__(self, paths: CuePaths, db: CueDatabase) -> None: ...
    def scan(self) -> None: ...
    def _scan_external(self) -> None: ...
    def _scan_external_root(self, abs_root: str, used_labels: List[str]) -> Dict[str, Any]: ...
    def _external_label(self, abs_root: str, used_labels: List[str]) -> str: ...
    def ref_from_display(self, display_path: str) -> str: ...
    def resolve_path(self, ref: str) -> str: ...
    def _rebuild_merged(self) -> None: ...
    def _merged_tree(self) -> List[Dict[str, Any]]: ...
    def toggle_file_enabled(self, full_path: str) -> None: ...
    def toggle_file_ref_expand(self, folder_ref: str) -> None: ...
    def count_file_list_rows(
        self, folder_label: Optional[str], folder_children: Optional[List[str]], files: List[str]
    ) -> int: ...
    def toggle_presets_expand(self) -> None: ...
    def toggle_preset_expand(self, preset_name: str) -> None: ...
    def toggle_video_presets_expand(self) -> None: ...
    def toggle_video_preset_expand(self, preset_name: str) -> None: ...
    def toggle_video_pool_expand(self, preset_name: str, pool_index: int) -> None: ...
    def toggle_igroups_expand(self) -> None: ...
    def toggle_igroup_expand(self, group_name: str) -> None: ...
    def add_level(self, group_name: str) -> None: ...
    def toggle_ilevel_add_mode(self, group_name: str, ilevel_id: int) -> None: ...
    def toggle_ilevel_expand(self, group_name: str, ilevel_id: int) -> None: ...
    def _ilevel_target_valid(self, group_name: str, ilevel_id: int) -> bool: ...
    def ilevel_add_file(self, group_name: str, ilevel_id: int, file_ref: str) -> None: ...
    def ilevel_add_folder(self, group_name: str, ilevel_id: int, folder_path: str) -> None: ...
    def level_has_file(self, group_name: str, ilevel_id: int, file_ref: str) -> bool: ...
    def tree_rows(self, *state: object) -> List[Dict[str, Any]]: ...
    def content_rows(
        self,
        search_query: str,
        preset_names: List[str],
        video_preset_names: List[str],
        igroup_names: List[str],
        is_video: bool,
        tgt_ok: bool,
        unplayable: Dict[str, str],
    ) -> List[Dict[str, Any]]: ...
    def set_add_to_pool_warning(self, message: str) -> None: ...
    def clear_add_to_pool_warning(self) -> None: ...
    def toggle_sidebar_mode(self) -> None: ...
    def persist_sidebar_state(self) -> None: ...
    def set_sidebar_width(self, width: int) -> None: ...
    def _encode_ui_state(self) -> Dict[str, Any]: ...
    def save_ui_state(self) -> None: ...
    def _apply_ui_state(self, blob: Optional[Dict[str, Any]]) -> None: ...
    def restore_ui_state(self) -> None: ...

class CueSfxManager(object):
    library: CueSfxLibraryTree
    _paths: CuePaths
    _db: CueDatabase
    _volume: CueVolumeManager
    _ctx: CueContext
    _supports_relative_volume: bool
    _markers: Optional[CueMarkerManager]
    _next_sfx_channel: int
    _preview_channel: Optional[str]
    _wav_playable: CueWavPlayable
    _warm_thread: Optional[Any]

    def __init__(
        self,
        paths: CuePaths,
        db: CueDatabase,
        volume: CueVolumeManager,
        ctx: CueContext,
        supports_relative_volume: bool,
    ) -> None: ...
    def bind_markers(self, markers: CueMarkerManager) -> None: ...
    def _markers_ctx(self) -> CueMarkerManager: ...
    def warm_cache(self) -> None: ...
    def unplayable_files(self) -> Dict[str, str]: ...
    def play_sfx(
        self,
        filename: str,
        source: str = "",
        volume: float = 1.0,
        marker_time: Optional[float] = None,
        marker_elapsed: Optional[float] = None,
        marker_delta: Optional[float] = None,
    ) -> Optional[str]: ...
    def preview_sfx(self, filename: str, volume: float = 1.0) -> None: ...
    def play_pool(
        self,
        entry: Optional[MarkerEntry],
        key: str,
        pool: PoolDict,
        pool_index: int,
        file: Optional[str] = None,
        avoid_repeats: bool = True,
        volume_mult: Optional[float] = None,
        marker_time: Optional[float] = None,
        marker_elapsed: Optional[float] = None,
        marker_delta: Optional[float] = None,
    ) -> Optional[str]: ...
    def fade_out(
        self, exclude_channels: Optional[List[str]] = None, only_channels: Optional[List[str]] = None
    ) -> int: ...
    def preview_preset(self, preset_name: str) -> None: ...
    def preview_folder(self, folder_path: str, volume: float = 1.0) -> None: ...
    def preview_level(self, group_name: str, ilevel_id: int) -> None: ...
    def preview_video_preset(self, preset_name: str) -> None: ...
    def preview_video_pool(self, preset_name: str, pool_index: int) -> None: ...
