# Type stub for cue_lib.audio.sfx_manager
from typing import Dict, List, Optional, Set

from cue_lib.audio.audio_tree import CueAudioTreeManager
from cue_lib.db import CueDatabase
from cue_lib.paths import CuePaths

class CueSfxManager(CueAudioTreeManager):
    expanded_file_refs: Dict[str, bool]
    presets_expanded: bool
    expanded_presets: Dict[str, bool]
    video_presets_expanded: bool
    expanded_video_presets: Dict[str, bool]
    disabled_files: Set[str]
    overlay_mode: bool

    def __init__(self, paths: CuePaths, db: CueDatabase) -> None: ...
    def toggle_file_enabled(self, full_path: str) -> None: ...
    def toggle_file_ref_expand(self, folder_ref: str) -> None: ...
    def count_file_list_rows(
        self,
        folder_label: Optional[str],
        folder_children: Optional[List[str]],
        files: List[str]) -> int: ...
    def toggle_presets_expand(self) -> None: ...
    def toggle_preset_expand(self, preset_name: str) -> None: ...
    def toggle_video_presets_expand(self) -> None: ...
    def toggle_video_preset_expand(self, preset_name: str) -> None: ...
    def toggle_overlay_mode(self) -> None: ...
