# Type stub for cue_lib.audio.sync
from typing import Final, Tuple

from cue_lib.db import CueDatabase

CUE_SYNC_CHANNEL: Final = "cue_sync"
CUE_SYNC_CLICK: Final = "renpy_cue/cue_lib/assets/audio/metronome.mp3"
CUE_SYNC_STAGE_INTERVALS: Final = (1.0, 0.6, 0.4)
CUE_SYNC_STAGE_LABELS: Final = ("Slow", "Medium", "Fast")
CUE_SYNC_BEATS_PER_STAGE: Final = 3
CUE_SYNC_MARKER_FRACS: Final[Tuple[float, ...]] = (0.25, 0.5, 0.75)

class CueSyncManager:
    LEAD_MAX: float
    sync_lead: float
    is_running: bool
    stage_intervals: Tuple[float, float, float]

    def __init__(self, db: CueDatabase) -> None: ...
    def set_sync_lead(self, seconds: float) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def current_interval(self) -> float: ...
    def stage_label(self) -> str: ...
    def stage_duration(self) -> float: ...
    def phase(self, now: float) -> float: ...
    def tick(self, now: float) -> None: ...
