# Type stub for cue_lib.music.manager
from typing import Any, Dict, List, Optional, Tuple, Union

from cue_lib._types import DefaultMusicTrigger
from cue_lib.audio.recent import CueRecentManager
from cue_lib.audio.tree.music_tree import CueMusicTree
from cue_lib.audio.wav_playable import CueWavPlayable
from cue_lib.marker_store import CueMarkerStore
from cue_lib.preset_store import CuePresetStore
from cue_lib.state import CueContext
from cue_lib.db import CueDatabase
from cue_lib.paths import CuePaths

CUE_MUSIC_CROSSFADE: float

class CueMusicManager:
    _is_installed: bool
    last_event: Optional[Dict[str, Any]]
    _original_music_play: Any
    _original_music_queue: Any
    _original_music_stop: Any
    _triggers: Dict[str, List[DefaultMusicTrigger]]
    _pending: Optional[Dict[str, Any]]
    selected_key: Optional[str]
    _last_auto_scene: Optional[str]
    expanded_file_refs: Dict[str, bool]
    _music_presets: Dict[str, Any]
    presets_expanded: bool
    expanded_presets: Dict[str, bool]
    library: CueMusicTree
    _recent: CueRecentManager
    _store: CueMarkerStore
    _ctx: CueContext
    _db: CueDatabase
    _paths: CuePaths
    _wav_playable: CueWavPlayable
    _presets: CuePresetStore

    def __init__(
        self,
        ctx: CueContext,
        store: CueMarkerStore,
        db: CueDatabase,
        paths: CuePaths,
        presets: Optional[CuePresetStore] = None,
    ) -> None: ...
    def install(self) -> None: ...
    def _playable_file(self, path: str) -> str: ...
    def _convert_filename(self, fn: Union[str, List[str]]) -> Any: ...
    def _convert_play_file(self, args: tuple, kwargs: dict) -> tuple: ...
    def _play_music(self, args: tuple, kwargs: dict) -> Any: ...
    def play_untracked(self, full_path: str, volume: float = 1.0) -> None: ...
    def now_playing(self) -> Optional[str]: ...
    @property
    def is_paused(self) -> bool: ...
    def toggle_pause(self) -> None: ...
    def default_display_path(self, path: str) -> str: ...
    def load_triggers(self) -> None: ...
    def triggers_for(self, replay_id: Optional[str]) -> List[DefaultMusicTrigger]: ...
    def _current_scene_key(self) -> str: ...
    def capture_display(self) -> None: ...
    def select_trigger(self, key: str) -> None: ...
    def selected_trigger_label(self) -> str: ...
    def _current_scene_has_trigger(self, key: str) -> bool: ...
    def _resolve_selection(self) -> Optional[str]: ...
    def create_scene_trigger(self) -> Optional[str]: ...
    def default_path_for(self, key: str) -> Optional[List[str]]: ...
    def _default_trigger_by_key_before(self, key_before: str) -> Optional[DefaultMusicTrigger]: ...
    def _is_default_trigger_scene(self, key: str) -> bool: ...
    def resolve_music_files(self, files: List[str]) -> List[str]: ...
    def ref_path(self, ref: str) -> str: ...
    def _split_ref_tag(self, ref: str) -> Tuple[Optional[str], str]: ...
    def _resolve_music_path(self, stored: str) -> str: ...
    def music_pool_for(self, scene_key: str) -> List[str]: ...
    def add_user_song_to_trigger(self, path: str, record: bool = True) -> None: ...
    def add_game_song_to_trigger(self, path: str, record: bool = True) -> None: ...
    def add_external_song_to_trigger(self, abs_path: str, record: bool = True) -> None: ...
    def add_user_folder_to_trigger(self, folder_path: str, record: bool = True) -> None: ...
    def add_game_folder_to_trigger(self, folder_path: str, record: bool = True) -> None: ...
    def add_external_folder_to_trigger(self, abs_folder: str, record: bool = True) -> None: ...
    def _add_ref_to_trigger(self, ref: str, record: bool = True) -> None: ...
    def remove_song_from_trigger(self, key: str, path: str) -> None: ...
    def toggle_file_ref_expand(self, folder_ref: str) -> None: ...
    def remove_song_from_folder_ref(self, key: str, file_index: int, child_file: str) -> None: ...
    def toggle_default(self, key: str) -> None: ...
    def delete_trigger(self, key: str) -> None: ...
    def triggers(self) -> List[Dict[str, Any]]: ...
    def _pick_for_override(self) -> Any: ...
    def play_custom_music(self) -> None: ...
    def songs_for_trigger(self, key: str) -> List[str]: ...
    def apply_preset(self, name: str) -> None: ...
    def _set_trigger_songs(self, key: str, files: List[str]) -> None: ...
    def preset_remove_file(self, name: str, display_path: str) -> None: ...
    def preset_display_files(self, preset: Dict[str, Any]) -> List[str]: ...
    def _folder_display_children(self, folder_ref: str) -> List[str]: ...
    def toggle_presets_expand(self) -> None: ...
    def toggle_preset_expand(self, name: str) -> None: ...
    def save_ui_state(self) -> None: ...
    def restore_ui_state(self) -> None: ...
    def _on_play(self, *args: Any, **kwargs: Any) -> Any: ...
    def _on_queue(self, *args: Any, **kwargs: Any) -> Any: ...
    def _on_stop(self, *args: Any, **kwargs: Any) -> Any: ...
    def _record(self, event_type: str, args: tuple, kwargs: dict, channel_offset: int) -> None: ...
    def _record_default_trigger(self, filenames: Any, in_replay: Any) -> None: ...
    def preview_preset(self, preset_name: str) -> None: ...
