# Type stub for cue_lib.music.presets
from typing import Any, Dict, List

from cue_lib.music.manager import CueMusicManager
from cue_lib.audio.tree.music_tree import CueMusicTree
from cue_lib.marker_store import CueMarkerStore
from cue_lib.preset_store import CuePresetStore

class CueMusicPresetsUi:
    _mgr: CueMusicManager
    _presets: CuePresetStore
    _store: CueMarkerStore
    library: CueMusicTree
    presets_expanded: bool
    expanded_presets: Dict[str, bool]

    def __init__(self, mgr: CueMusicManager) -> None: ...
    def apply_preset(self, name: str) -> None: ...
    def _set_trigger_songs(self, key: str, files: List[str]) -> None: ...
    def preset_remove_file(self, name: str, display_path: str) -> None: ...
    def preset_display_files(self, preset: Dict[str, Any]) -> List[str]: ...
    def _folder_display_children(self, folder_ref: str) -> List[str]: ...
    def toggle_presets_expand(self) -> None: ...
    def toggle_preset_expand(self, name: str) -> None: ...
    def preview_preset(self, preset_name: str) -> None: ...
