# Type stub for cue_lib.music.refs
from typing import List, Optional, Tuple

from cue_lib.paths import CuePaths
from cue_lib.audio.tree.music_tree import CueMusicTree

def _cue_split_ref_tag(ref: str) -> Tuple[Optional[str], str]: ...
def _cue_ref_path(ref: str) -> str: ...
def _cue_resolve_music_path(paths: CuePaths, stored: str) -> str: ...
def _cue_resolve_music_files(library: CueMusicTree, files: List[str]) -> List[str]: ...
def _cue_resolve_folder_ref(library: CueMusicTree, folder_ref: str, result: List[str]) -> None: ...
def _cue_expand_folder_into(result: List[str], files: List[str], ref: str, tag: str) -> None: ...
