# Type stub for cue_lib.music.triggers
from typing import Any, Dict, List, Optional

from cue_lib._types import DefaultMusicTrigger
from cue_lib.music.manager import CueMusicManager
from cue_lib.audio.tree.music_tree import CueMusicTree
from cue_lib.marker_store import CueMarkerStore
from cue_lib.state import CueContext
from cue_lib.db import CueDatabase
from cue_lib.paths import CuePaths

_SUPPRESS_MUSIC: object

class CueMusicTriggers:
    _mgr: CueMusicManager
    _store: CueMarkerStore
    _ctx: CueContext
    _db: CueDatabase
    _paths: CuePaths
    library: CueMusicTree
    _triggers: Dict[str, List[DefaultMusicTrigger]]
    _pending: Optional[Dict[str, Any]]
    selected_key: Optional[str]
    _last_auto_scene: Optional[str]
    expanded_file_refs: Dict[str, bool]

    def __init__(self, mgr: CueMusicManager) -> None: ...
    def load_triggers(self) -> None: ...
    def triggers_for(self, replay_id: Optional[str]) -> List[DefaultMusicTrigger]: ...
    def _current_scene_key(self) -> str: ...
    def _record_default_trigger(self, filenames: Any, in_replay: Any) -> None: ...
    def capture_display(self) -> None: ...
    def select_trigger(self, key: str) -> None: ...
    def selected_trigger_label(self) -> str: ...
    def _current_scene_has_trigger(self, key: str) -> bool: ...
    def _resolve_selection(self) -> Optional[str]: ...
    def create_scene_trigger(self) -> Optional[str]: ...
    def default_path_for(self, key: str) -> Optional[List[str]]: ...
    def _default_trigger_by_key_before(self, key_before: str) -> Optional[DefaultMusicTrigger]: ...
    def _is_default_trigger_scene(self, key: str) -> bool: ...
    def music_pool_for(self, scene_key: str) -> List[str]: ...
    def add_user_song_to_trigger(self, path: str, record: bool = True) -> None: ...
    def add_game_song_to_trigger(self, path: str, record: bool = True) -> None: ...
    def add_external_song_to_trigger(self, abs_path: str, record: bool = True) -> None: ...
    def add_user_folder_to_trigger(self, folder_path: str, record: bool = True) -> None: ...
    def add_game_folder_to_trigger(self, folder_path: str, record: bool = True) -> None: ...
    def add_external_folder_to_trigger(self, abs_folder: str, record: bool = True) -> None: ...
    def _add_ref_to_trigger(self, ref: str, record: bool = True) -> None: ...
    def remove_song_from_trigger(self, key: str, path: str) -> None: ...
    def toggle_file_ref_expand(self, folder_ref: str) -> None: ...
    def remove_song_from_folder_ref(self, key: str, file_index: int, child_file: str) -> None: ...
    def toggle_default(self, key: str) -> None: ...
    def delete_trigger(self, key: str) -> None: ...
    def triggers(self) -> List[Dict[str, Any]]: ...
    def _pick_for_override(self) -> Any: ...
    def play_custom_music(self) -> None: ...
    def songs_for_trigger(self, key: str) -> List[str]: ...
