# Type stub for cue_lib.trigger.exclusive
from typing import Any, Dict, List, Optional

CUE_EXCL_KIND_LOOP: str
CUE_EXCL_KIND_ONESHOT: str
CUE_EXCL_KIND_VIDEO: str

class CueExclusiveRegistry:
    channels: Dict[str, Dict[str, Any]]

    def __init__(self) -> None: ...
    def prune(self) -> None: ...
    def in_same_group(self, info: Any, kind: str, scene: Optional[str], line: Optional[str]) -> bool: ...
    def group_channels(self, kind: str, scene: Optional[str], line: Optional[str]) -> List[str]: ...
    def kind_channels(self, kind: str) -> List[str]: ...
    def is_hold_blocked(self, kind: str, scene: Optional[str], line: Optional[str]) -> bool: ...
    def is_outgroup_busy(self, kind: str, scene: Optional[str], line: Optional[str]) -> bool: ...
    def track_channel(
        self, channel: Optional[str], kind: str, scene: Optional[str], line: Optional[str], hold: bool
    ) -> None: ...
