# Type stub for cue_lib.trigger.helpers
from typing import List, Optional

from cue_lib.intensity import CueIntensityResolution
from cue_lib.marker_store import CueMarkerStore

CUE_MARKER_LEAD_MAX: float
CUE_SFX_AUDIBLE_LEAD: float

def _cue_loop_still_playing(channels: List[str]) -> bool: ...
def _cue_pick_deduped(files: List[str], picked: List[str], max_tries: int = 3) -> Optional[str]: ...
def _cue_pick_loop_deduped(files: List[str], picked: List[str], recent: List[str]) -> Optional[str]: ...
def _cue_marker_lead(tick_interval: float, speed: float, audible_lead: float = ...) -> float: ...
def _cue_marker_reached(
    mt: float, effective_elapsed: float, prev_eff: float, marker_tolerance: float, lead: float = 0.0
) -> bool: ...
def _cue_effective_delay(base_delay: float, level_mult: float) -> float: ...
def _cue_vid_intensity_resolution(
    store: CueMarkerStore, current_file: str, speed: float, variants: Optional[List[float]]
) -> Optional[CueIntensityResolution]: ...
