from typing import Any, Callable, Optional, Tuple

class DynamicDisplayable:
    def __init__(self, callback: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...

class Container:
    def __init__(self, **properties: Any) -> None: ...
    children: list[Any]
    offsets: list[Tuple[int, int]]
    def add(self, child: Any) -> None: ...
    def render(self, width: int, height: int, st: float, at: float) -> Any: ...
    def event(self, ev: Any, x: int, y: int, st: float) -> Optional[Any]: ...
    def visit(self) -> list[Any]: ...

class Window:
    def __init__(self, style: Any = None, **properties: Any) -> None: ...
    def add(self, child: Any) -> None: ...
