# Type stub for cue_lib.backup
from typing import Any, Callable, Final, List, Optional, Tuple

from cue_lib.paths import CuePaths

CUE_BACKUP_INTERVAL: Final = 3600
CUE_BACKUP_MAX: Final = 720
CUE_BACKUP_PREFIX: Final = "auto_backup_"
CUE_MANUAL_BACKUP_NAME: Final = "renpy_cue_backup.zip"
CUE_BAK_DIR: Final = "data_bak"
CUE_RESTORE_TMP_DIR: Final = "_restore_tmp"
CUE_MEDIA_DIRS: Final = ("audio", "music")
CUE_VIDEO_DIR: Final = "video"

def _backup_ts_from_name(name: str) -> Optional[int]: ...
def _safe_extract_path(out_dir: str, name: str) -> Optional[str]: ...

def zip_tree(data_dir: str, zip_path: str, tmp_path: Optional[str] = None) -> int: ...
def zip_shared_tree(
    root: str,
    zip_path: str,
    tmp_path: Optional[str] = None,
    progress: Optional[Callable[[int, int], None]] = None,
) -> int: ...
def validate_backup_zip(zip_path: str) -> Tuple[bool, str]: ...
def extract_matching(zip_path: str, out_dir: str, matchers: List[str]) -> int: ...
def restore_pieces(zip_path: str, shared_dir: str, game_id: str) -> int: ...
def restore_counts(zip_path: str, shared_dir: str, game_id: str) -> Tuple[int, int]: ...
def restore_confirm_message(overwritten: int, added: int) -> str: ...

class CueAutoBackupManager(object):
    _owner: CueBackupManager
    _last_backup_ts: float
    _backup_in_progress: bool
    enabled: bool

    def __init__(self, owner: "CueBackupManager") -> None: ...
    def _backups_dir(self) -> str: ...
    def _latest_backup_timestamp(self) -> float: ...
    def maybe(self) -> None: ...
    def force_backup(self) -> None: ...
    def wait_until_idle(self, timeout: float = 10.0) -> bool: ...
    def _run_backup(self) -> None: ...
    def _prune_backups(self) -> None: ...

class CueManualBackupManager(object):
    _owner: CueBackupManager
    _db: Any
    _reload_work: Optional[Callable[[int], None]]
    _confirm_dialog: Any
    is_backing_up: bool
    backup_fraction: float
    is_restoring: bool
    backup_status: str
    backup_error: str
    restore_status: str
    restore_error: str
    _backup_thread: Any
    _restore_thread: Any
    _restore_pending: bool
    _restore_count: int
    _restore_checking: bool
    _confirm_pending: bool
    _confirm_payload: Optional[Tuple[str, int, int]]

    def __init__(self, owner: "CueBackupManager") -> None: ...
    def wire(self, db: Any, reload_work: Callable[[int], None], confirm_dialog: Any) -> None: ...
    @property
    def is_restore_checking(self) -> bool: ...
    @property
    def is_busy(self) -> bool: ...
    def backup(self) -> None: ...
    def _backup_worker(self) -> None: ...
    def _zip_to_file(self) -> int: ...
    def _set_backup_progress(self, written: int, total: int) -> None: ...
    def restore(self) -> None: ...
    def _restore_check_worker(self, zip_path: str) -> None: ...
    def _apply_restore(self, zip_path: str) -> None: ...
    def _restore_worker(self, zip_path: str) -> None: ...
    def poll(self) -> None: ...
    def _finish_confirm(self) -> None: ...
    def _finish_reload(self) -> None: ...

class CueBackupManager(object):
    _paths: CuePaths
    _db: Any
    auto: CueAutoBackupManager
    manual: CueManualBackupManager

    def __init__(self, paths: CuePaths) -> None: ...
    def wire(self, db: Any, reload_work: Callable[[int], None], confirm_dialog: Any) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def game_id(self) -> str: ...
    def backups_root(self) -> str: ...

    def maybe(self) -> None: ...
    def force_backup(self) -> None: ...
    def wait_until_idle(self, timeout: float = 10.0) -> bool: ...
    def set_auto_backups(self, enabled: bool) -> None: ...

    def backup(self) -> None: ...
    def restore(self) -> None: ...
    def poll(self) -> None: ...

    @property
    def is_backing_up(self) -> bool: ...
    @property
    def backup_fraction(self) -> float: ...
    @property
    def is_restoring(self) -> bool: ...
    @property
    def is_restore_checking(self) -> bool: ...
    @property
    def is_busy(self) -> bool: ...
    @property
    def backup_status(self) -> str: ...
    @property
    def backup_error(self) -> str: ...
    @property
    def restore_status(self) -> str: ...
    @property
    def restore_error(self) -> str: ...
