# Type stub for cue_lib.backup
from typing import Final, List, Optional, Tuple

CUE_BACKUP_INTERVAL: Final = 3600
CUE_BACKUP_MAX: Final = 100
CUE_BACKUP_DIR: Final = "backups"
CUE_BACKUP_AUTO_DIR: Final = "auto"
CUE_BACKUP_PREFIX: Final = "auto_backup_"
CUE_MANUAL_BACKUP_NAME: Final = "backup.zip"
CUE_BAK_DIR: Final = "data_bak"
CUE_RESTORE_TMP_DIR: Final = "_restore_tmp"
CUE_MEDIA_DIRS: Final = ("audio", "music")

def zip_tree(data_dir: str, zip_path: str, tmp_path: Optional[str] = None) -> int: ...
def zip_shared_tree(root: str, zip_path: str, tmp_path: Optional[str] = None) -> int: ...
def validate_backup_zip(zip_path: str) -> Tuple[bool, str]: ...
def extract_matching(zip_path: str, out_dir: str, matchers: List[str]) -> int: ...
def restore_pieces(zip_path: str, shared_dir: str, game_id: str) -> int: ...

class CueBackupManager(object):
    def __init__(self, path: str, game_id: str) -> None: ...
    def maybe(self) -> None: ...
    def force_backup(self) -> None: ...
    def wait_until_idle(self, timeout: float = 10.0) -> bool: ...
