from typing import Final

CUE_SFX_CHANNEL_COUNT: Final = 8
CUE_MAX_INTERP_FPS: Final = 60
CUE_DEFAULT_VIDEO_SPEED: Final = 1.0
CUE_MULTI_SPEED_MIN_VARIANTS: Final = 2
CUE_POPPER_DEFAULT_OFFSET: Final = 5
CUE_POPPER_DEFAULT_MARGIN: Final = 8
CUE_AUTO_SPEED_MIN_VARIANTS: Final = 4
CUE_AUTO_SPEED_IDEAL_VARIANTS: Final = 8
