from typing import Final

CUE_SFX_CHANNEL_COUNT: Final = 8
CUE_MAX_INTERP_FPS: Final = 60
CUE_DEFAULT_VIDEO_SPEED: Final = 1.0
CUE_MIN_SPEEDS_FOR_SEQUENCE: Final = 2
CUE_POPPER_DEFAULT_OFFSET: Final = 5
CUE_POPPER_DEFAULT_MARGIN: Final = 8
