from typing import Any, Dict, Tuple

class CueDatabase(object):
    BACKUP_RETENTION_DAYS: int

    def __init__(self, path: str, game_id: str) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def is_open(self) -> bool: ...

    @property
    def path(self) -> str: ...
    @property
    def game_id(self) -> str: ...

    def is_fresh(self) -> bool: ...
    def migrate_markers_and_presets(
        self,
        markers: Dict[str, Any],
        presets: Dict[str, Any],
        video_presets: Dict[str, Any],
    ) -> None: ...

    def load_markers(self) -> Dict[str, Any]: ...
    def save_marker(self, key: str, entry: Any) -> None: ...
    def delete_marker(self, key: str) -> None: ...

    def load_presets(self) -> Tuple[Dict[str, Any], Dict[str, Any]]: ...
    def save_preset(self, preset_type: str, name: str, data: Any) -> None: ...
    def delete_preset(self, preset_type: str, name: str) -> None: ...

    def maybe_backup(
        self,
        markers: Dict[str, Any],
        presets: Dict[str, Any],
        video_presets: Dict[str, Any],
    ) -> None: ...


def _cue_get_shared_dir() -> str: ...
def _cue_open_database(game_id: str) -> CueDatabase: ...
