from typing import Any, Dict, Final, Optional, Tuple

from cue_lib.backup import CueBackupManager
from cue_lib.paths import CuePaths

CUE_HASH_TRUNC_LEN: Final = 8
CUE_DEFAULT_MUSIC_TRIGGERS_FILENAME: Final = "default_music_triggers.json"

def _key_to_filename(key: str) -> str: ...

def _atomic_json_write(fpath: str, data: Any, indent: Optional[int] = None) -> None: ...

class CueDatabase(object):
    _backup: CueBackupManager
    paths: CuePaths

    def __init__(self, paths: CuePaths) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def is_open(self) -> bool: ...

    def load_markers(self) -> Dict[str, Any]: ...
    def save_marker(self, key: str, entry: Any) -> None: ...
    def delete_marker(self, key: str) -> None: ...

    def load_presets(self) -> Tuple[Dict[str, Any], Dict[str, Any]]: ...
    def load_music_presets(self) -> Dict[str, Any]: ...
    def save_preset(self, preset_type: str, name: str, data: Any) -> None: ...
    def delete_preset(self, preset_type: str, name: str) -> None: ...
    def preset_file_matches(self, preset_type: str, name: str, expected: Any) -> bool: ...

    def load_shared_config(self) -> Dict[str, Any]: ...
    def save_shared_config(self, data: Dict[str, Any]) -> None: ...
    def update_shared_config(self, data: Dict[str, Any]) -> None: ...
    def set_auto_backups(self, enabled: bool) -> None: ...

    def _music_triggers_path(self) -> str: ...
    def load_default_music_triggers(self) -> Dict[str, Any]: ...
    def save_default_music_triggers(self, data: Dict[str, Any]) -> None: ...
    def update_default_music_triggers(
        self, replay_id: str, key_before: str, path: str, key_after: Optional[str] = None
    ) -> None: ...
