# Type stub for cue_lib.dialogues
from typing import Callable, Optional

from cue_lib._types import MarkerEntry  # pyright: ignore[reportUnusedImport]

class CuePresetDialog:
    trigger_key: Optional[str]
    pool_idx: int
    name: str

    def __init__(self) -> None: ...
    def open(self, trigger_key: str, pool_idx: int) -> None: ...
    def commit(self) -> None: ...
    def cancel(self) -> None: ...

class CueVideoPresetDialog:
    name: str

    def __init__(self) -> None: ...
    def open(self) -> None: ...
    def commit(self) -> None: ...
    def cancel(self) -> None: ...

class CueConfirmDialog:
    message: str
    on_confirm: Optional[Callable[..., None]]

    def __init__(self) -> None: ...
    def show(self, message: str, confirm_action: Callable[..., None]) -> None: ...
    def hide(self) -> None: ...

def _cue_confirm_delete_preset(preset_name: str) -> None: ...
def _cue_confirm_delete_video_preset(preset_name: str) -> None: ...
def _cue_maybe_apply_video_preset(preset_name: str) -> None: ...
def _cue_preview_video_preset(preset_name: str) -> None: ...

def _cue_make_tab_action(fn: Callable[..., None], args_tuple: tuple, pi: int) -> Callable[..., None]: ...
def _cue_count_file_list_rows(folder_label: Optional[str], folder_children: Optional[list[str]], files: list[str]) -> int: ...
