# Type stub for cue_lib.file_tree
from typing import Any, Dict, List, Set

class CueFileTreeManager:
    visible_tree: List[Dict[str, Any]]
    expanded_folders: Dict[str, bool]
    expanded_file_refs: Dict[str, bool]
    presets_expanded: bool
    expanded_presets: Dict[str, bool]
    video_presets_expanded: bool
    expanded_video_presets: Dict[str, bool]
    collapsed_sections: Dict[str, bool]
    disabled_files: Set[str]

    def __init__(self) -> None: ...
    def rebuild_tree(self) -> None: ...
    def toggle_folder(self, folder_path: str) -> None: ...
    def toggle_file_enabled(self, full_path: str) -> None: ...
    def toggle_file_ref_expand(self, folder_ref: str) -> None: ...
    def toggle_presets_expand(self) -> None: ...
    def toggle_preset_expand(self, preset_name: str) -> None: ...
    def toggle_video_presets_expand(self) -> None: ...
    def toggle_video_preset_expand(self, preset_name: str) -> None: ...
    def toggle_section(self, section_name: str) -> None: ...
