# Type stub for cue_lib.importer_io
from typing import Any, Dict, Final, List, Optional, Set, Tuple

CUE_IMPORT_FORMAT_VERSION: Final = 1

def _cue_import_category(path: str) -> int: ...
def _cue_known_content(path: str) -> bool: ...
def _cue_digit_strip_normalize(game_id: str) -> str: ...
def _cue_import_match(game_id: str, manifest_game_id: str) -> Tuple[int, str]: ...
def _cue_group_contents(contents: List[str]) -> Dict[int, List[str]]: ...
def _cue_category_counts(contents: List[str]) -> Dict[int, int]: ...
def _cue_empty_categories(contents: List[str]) -> List[int]: ...
def _cue_filter_contents(contents: List[str], checked_categories: Any) -> List[str]: ...
def _cue_build_manifest(
    game_id: str, name: str, author: str, description: str,
    contents: List[str], replays: Optional[List[dict]] = None,
) -> dict: ...
def _cue_manifest_replays(root: str, game_id: str, contents: List[str]) -> List[dict]: ...
def _cue_validate_manifest(manifest: Any, zip_names: Any) -> Tuple[bool, str]: ...
def _cue_missing_files(manifest: Any, zip_names: Any) -> List[str]: ...
def _cue_load_manifest(imp_dir: str) -> Any: ...
def _cue_zip_file_names(zip_path: str) -> Set[str]: ...
def _cue_sanitize_filename(name: str) -> str: ...
def _cue_collect_tree(root: str, src_dir: str) -> List[str]: ...
def _cue_enumerate_import_files(root: str, game_id: str) -> Dict[int, List[str]]: ...
def _cue_replay_assets(
    root: str, game_id: str, replay_labels: List[str],
) -> Dict[int, List[str]]: ...
def _cue_replay_labels(root: str, game_id: str) -> List[Tuple[str, int]]: ...
def _cue_audio_rel(ref: str) -> str: ...
def _cue_music_rel(song: str) -> Optional[str]: ...
def _cue_build_import_zip(
    root: str, game_id: str, name: str, author: str, description: str,
    contents: List[str], zip_path: str, progress: Any = None,
) -> int: ...
def _cue_extract_import_zip(
    zip_path: str, out_dir: str, progress: Any = None,
) -> int: ...
def _cue_copy_file(src: str, dst: str) -> None: ...
def _cue_merge_overwrites(root: str, contents: List[str]) -> List[str]: ...
def _cue_merge_files(root: str, src_root: str, contents: List[str]) -> int: ...
