# Type stub for cue_lib.importer
from typing import Any, Callable, List, Optional, Tuple

def _imp_file_names(imp_dir: str) -> set: ...
def _cue_rename_if_exists(src: str, dst: str) -> None: ...
def _cue_rewrite_rel(rel: str, old_gid: str, new_gid: str) -> str: ...
def _zip_mtime(zip_path: str) -> float: ...

class CueImportManager(object):
    imports: List[dict]
    scan_error: str
    is_active: bool
    active_import: Optional[str]
    merge_status: str
    is_scanning: bool
    _scan_thread: Any
    is_importing: bool
    import_label: str
    import_fraction: float

    def __init__(self, paths: Any, db: Any, refresh_overlay: Callable[[], None]) -> None: ...
    def imports_dir(self) -> str: ...
    def imports_unzip_dir(self) -> str: ...
    def _imp_dir(self, imp: str) -> str: ...
    def scan(self) -> None: ...
    def _kick_scan_thread(self) -> None: ...
    def _scan_worker(self) -> None: ...
    def _do_scan(self) -> None: ...
    def _set_import_progress(self, written: int, total: int) -> None: ...
    def _sort_key(self, entry: dict) -> Tuple[int, float]: ...
    def import_for(self, imp: str) -> Optional[dict]: ...
    def active_import_name(self) -> str: ...
    def match_label(self, imp: str) -> str: ...
    def match_warnings(self, imp: str) -> List[str]: ...
    def activate(self, imp: str) -> None: ...
    def _do_activate(self, imp: str) -> None: ...
    def deactivate(self) -> None: ...
    def remap(self, imp: str) -> None: ...
    def confirm_delete(self, imp: str) -> None: ...
    def delete_confirmed(self, imp: str) -> None: ...
    def open_merge(self, imp: str) -> None: ...
    def merge_confirm(self, imp: str, checked: Any) -> None: ...
    def folder_files(self, imp: str) -> List[str]: ...
