from typing import Dict, Final, List

from cue_lib.db import CueDatabase

# Bridge functions
def _cue_keybind_start(action_id: str) -> None: ...
def _cue_keybind_cancel() -> None: ...
def _cue_keybind_reset(action_id: str) -> None: ...

class CueKeybindsManager(object):
    actions: Final[List[Dict[str, str]]]
    collision_message: str

    def __init__(self, db: CueDatabase) -> None: ...
    def setup(self) -> None: ...
    def get_keysym(self, action_id: str) -> str: ...
    def keysym_label(self, keysym: str) -> str: ...
    def visible_actions(self) -> List[Dict[str, str]]: ...
    def current_label(self) -> str: ...
    def shortcut_label(self, action_id: str) -> str: ...
    def start_capture(self, action_id: str) -> None: ...
    def cancel_capture(self) -> None: ...
    def on_captured(self, keysym: str) -> None: ...
    def reset_binding(self, action_id: str) -> None: ...
    def save(self) -> None: ...
