# Type stub for cue_lib.logger
from typing import Any, List

class CueLogger:
    _buffer: List[str]
    _lock: Any

    def __init__(self, lock: Any = None) -> None: ...
    def log(self, msg: str) -> None: ...
    def flush(self) -> None: ...
    def clear_debug(self) -> None: ...
    def log_error(self, msg: str) -> None: ...
    def clear_error(self) -> None: ...

_cue_logger: CueLogger
