# Type stub for cue_lib.logger
from typing import Any, Deque, Final, List

CUE_DEBUG_LOG_FILENAME: Final = "debug.log"
CUE_ERROR_LOG_FILENAME: Final = "error.log"
CUE_TRIGGER_DEBUG_FILENAME: Final = "trigger-debug.log"
CUE_TRIGGER_SNAPSHOT_LINES: Final = 150

class CueLogger:
    _buffer: List[str]
    _ring: Deque[str]
    _lock: Any

    def __init__(self, lock: Any = None) -> None: ...
    def log(self, msg: str) -> None: ...
    def flush(self) -> None: ...
    def clear_debug(self) -> None: ...
    def snapshot_debug(self, marker: str) -> None: ...
    def log_error(self, msg: str) -> None: ...
    def clear_error(self) -> None: ...

_cue_logger: CueLogger
