# Type stub for cue_lib.markers
from typing import Any, Dict, List, Optional, Set, Tuple

# Module-level binding of the stdlib random module (import random as _random
# in the source). Declared as Any so tests can monkeypatch it.
_random: Any

# Re-exported from their canonical homes: enum classes live in
# cue_lib.constants, the data layer + resolve snapshots in cue_lib.marker_store.
# Consumers (screens, trigger.py, tests) import them from cue_lib.markers.
# The `as X` form is pyright's explicit re-export -- plain imports from a stub
# are not re-exported when implicitReexport is off.
from cue_lib.constants import (
    CueExclusiveStart as CueExclusiveStart,
    CueLoopFrequency as CueLoopFrequency,
)
from cue_lib.marker_store import (
    CueMarkerStore as CueMarkerStore,
    ResolvedExclusive as ResolvedExclusive,
    ResolvedPool as ResolvedPool,
)

# All TypedDicts are defined in cue_lib._types (the single canonical source)
# and re-exported here for consumers that import from cue_lib.markers.
from cue_lib._types import (
    ClipboardData,
    MarkerEntry,
    PoolDict,
    VideoPoolDict,
    VideoPreset,
)


# Bootstrap / coordinator functions.  They write to managers wired after
# CueMarkerManager (trigger, etc.), so they live at module level and read _cue.
def _cue_load_scalars_from_persistent() -> None: ...
def _cue_paste_context() -> None: ...


# =========================================================================
# Context classes
# =========================================================================

class CueMarkerContext:
    def __init__(self, manager: "CueMarkerManager") -> None: ...
    def add_file(self, file_index: int) -> None: ...
    def remove_file(self, pool_index: int, file_index: int) -> None: ...
    def clear(self) -> None: ...
    def add_pool(self) -> None: ...
    def remove_pool(self, pool_index: int) -> None: ...
    def get_active(self) -> int: ...
    def set_active(self, pool_index: int) -> None: ...
    def get_active_pool(self) -> PoolDict: ...
    def has_pools(self) -> bool: ...
    def set_exclusive(self, start: int, hold: bool) -> None: ...
    def toggle_exclusive(self) -> None: ...
    def apply_preset(self, preset_name: str) -> None: ...
    def add_folder(self, folder_path: str) -> None: ...
    def send_file(self, file_index: int) -> None: ...
    def send_folder(self, folder_path: str) -> None: ...
    def send_preset(self, preset_name: str) -> None: ...

    # Internal (white-box tests exercise the pool helpers directly)
    _mgr: "CueMarkerManager"
    def _key(self) -> str: ...
    def _get_target(self) -> int: ...
    def _set_target(self, value: int) -> None: ...
    def _entry_and_pools(self) -> Tuple[Optional[MarkerEntry], List[Dict[str, Any]]]: ...
    def _sort_and_track(self, pools: List[Dict[str, Any]], tracked_entry: Dict[str, Any]) -> int: ...
    def _append_pool(self, entry: MarkerEntry, pools: List[Dict[str, Any]], pool_dict: Dict[str, Any]) -> None: ...

class CueImageContext(CueMarkerContext): ...
class CueDialogueContext(CueMarkerContext): ...

class CueVideoContext(CueMarkerContext):
    target_pool: int
    selected: Set[int]
    edit_text: str

    def __init__(self, manager: "CueMarkerManager") -> None: ...
    def add_file(self, file_index: int) -> None: ...
    def add_folder(self, folder_path: str) -> None: ...
    def add_pool(self) -> None: ...
    def apply_preset(self, preset_name: str) -> None: ...
    def apply_preset_active(self, preset_name: str) -> None: ...
    def send_preset(self, preset_name: str) -> None: ...
    def clear(self) -> None: ...
    def commit_text(self) -> None: ...
    def duplicate_pool(self, ts_index: int) -> None: ...
    def finalize_drag(self) -> None: ...
    def get_delete_message(self) -> str: ...
    def get_duration(self) -> float: ...
    def get_markers(self) -> List[VideoPoolDict]: ...
    def get_selected(self) -> Set[int]: ...
    def has_markers(self) -> bool: ...
    def nudge(self, delta: float) -> None: ...
    def remove_file(self, pool_index: int, file_index: int) -> None: ...
    def remove_pool(self, pool_index: int) -> None: ...
    def remove_selected(self) -> None: ...
    def select_tab(self, pool_index: int) -> None: ...
    def set_active(self, pool_index: int) -> None: ...
    def set_time(self, idx: int, new_time: float) -> None: ...
    def sync_text(self) -> None: ...

class CueLoopContext(CueMarkerContext):
    def __init__(self, manager: "CueMarkerManager") -> None: ...
    def add_pool(self) -> None: ...
    def clear(self) -> None: ...
    def set_frequency(self, freq: int) -> None: ...

    @staticmethod
    def get_delay(frequency: int = CueLoopFrequency.NORMAL) -> float: ...


# =========================================================================
# CueMarkerManager
# =========================================================================

class CueMarkerManager:
    image: CueImageContext
    dialogue: CueDialogueContext
    video: CueVideoContext
    loop: CueLoopContext
    clipboard: Optional[ClipboardData]

    def __init__(self, store: CueMarkerStore) -> None: ...
    def get(self, key: str, default: Optional[MarkerEntry] = None) -> Optional[MarkerEntry]: ...
    def setdefault(self, key: str, default: MarkerEntry) -> MarkerEntry: ...
    def pop(self, key: str, *args: MarkerEntry) -> MarkerEntry: ...
    def items(self) -> List[Tuple[str, MarkerEntry]]: ...
    def keys(self) -> List[str]: ...

    def create_preset(self, name: str, pool_dict: PoolDict) -> None: ...
    def delete_preset(self, name: str) -> None: ...
    def reload_presets(self) -> None: ...
    def preset_remove_file(self, name: str, file_path: str) -> None: ...
    def get_preset(self, name: str) -> Optional[PoolDict]: ...
    def list_presets(self) -> List[str]: ...

    def create_video_preset(self, name: str, entry: MarkerEntry) -> None: ...
    def delete_video_preset(self, name: str) -> None: ...
    def get_video_preset(self, name: str) -> Optional[VideoPreset]: ...
    def list_video_presets(self) -> List[str]: ...
    def video_preset_out_of_range(self, name: str) -> int: ...
    def apply_video_preset(self, name: str) -> None: ...

    def resolve_pool(self, pool: PoolDict) -> ResolvedPool: ...

    def save_marker(self, key: str) -> None: ...
    def save_markers(self, keys: List[str]) -> None: ...
    def save_preset(self, name: str) -> None: ...
    def save_video_preset(self, name: str) -> None: ...
    def save_all(self) -> None: ...
    def delete_removed_files(
        self,
        old_marker_keys: Set[str],
        old_presets: Dict[str, Any],
        old_video_presets: Dict[str, Any],
        old_session_created: Set[Tuple[str, str]]) -> None: ...
    def load_persistent(self) -> None: ...
    def backup_to_file(self) -> None: ...
    def restore_from_file(self) -> None: ...

    def copy_context(self) -> None: ...
    def paste_context(self) -> None: ...

    # Internal (accessed within cue_lib package)
    _store: CueMarkerStore
    _img_target: int
    _dlg_target: int
    _loop_target: int

    @property
    def _data(self) -> Dict[str, MarkerEntry]: ...
    @_data.setter
    def _data(self, value: Dict[str, MarkerEntry]) -> None: ...
    @property
    def _presets(self) -> Dict[str, PoolDict]: ...
    @_presets.setter
    def _presets(self, value: Dict[str, PoolDict]) -> None: ...
    @property
    def _video_presets(self) -> Dict[str, VideoPreset]: ...
    @_video_presets.setter
    def _video_presets(self, value: Dict[str, VideoPreset]) -> None: ...
    @property
    def _session_created(self) -> Set[Tuple[str, str]]: ...
    @_session_created.setter
    def _session_created(self, value: Set[Tuple[str, str]]) -> None: ...

    def _apply_restore(self, zip_path: str) -> None: ...
    def _get_or_create_entry(self, trigger_key: str) -> MarkerEntry: ...
    def _ensure_pool(self, trigger_key: str, pool_index: int) -> PoolDict: ...
    def _detach_pool(self, trigger_key: str, pool_index: int) -> bool: ...
    def _resolve_video_pools(self, entry: Any) -> List[VideoPoolDict]: ...
    def detach_active_video_ts(self, *args: Any) -> None: ...
    def detach_pool_at(self, trigger_key: str, pool_index: int) -> None: ...
