# Type stub for cue_lib.marker_store
from typing import Any, Callable, Dict, ItemsView, KeysView, List, Optional, Set, Tuple

from cue_lib._types import MarkerEntry, PoolDict, VideoPoolDict, VideoPreset
from cue_lib.db import CueDatabase
from cue_lib.paths import CuePaths

# =========================================================================
# Resolve snapshots
# =========================================================================

class ResolvedExclusive:
    """Resolved exclusive config snapshot. group 0 = Off."""

    group: int
    start: int
    hold: bool
    def __init__(self, group: int = 0, start: int = 0, hold: bool = False) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...

class ResolvedPool:
    """Immutable pool snapshot after resolving presets."""

    files: List[str]
    volume: float
    frequency: int
    trigger_on_shake: bool
    exclusive: ResolvedExclusive
    def __init__(
        self,
        files: List[str],
        volume: float,
        frequency: int,
        trigger_on_shake: bool,
        exclusive: Optional[ResolvedExclusive] = None,
    ) -> None: ...

# =========================================================================
# CueMarkerStore
# =========================================================================

class CueMarkerStore:
    _db: Optional[CueDatabase]
    _paths: CuePaths
    _on_save: Optional[Callable[[], None]]
    _data: Dict[str, MarkerEntry]
    _presets: Dict[str, PoolDict]
    _video_presets: Dict[str, VideoPreset]
    _session_created: Set[Tuple[str, str]]

    def __init__(
        self, db: Optional[CueDatabase], paths: CuePaths, on_save: Optional[Callable[[], None]] = None
    ) -> None: ...

    # Dict-like surface
    def __getitem__(self, key: str) -> MarkerEntry: ...
    def __setitem__(self, key: str, value: MarkerEntry) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def get(self, key: str, default: Optional[MarkerEntry] = None) -> Optional[MarkerEntry]: ...
    def setdefault(self, key: str, default: MarkerEntry) -> MarkerEntry: ...
    def pop(self, key: str, *args: MarkerEntry) -> MarkerEntry: ...
    def items(self) -> ItemsView[str, MarkerEntry]: ...
    def keys(self) -> KeysView[str]: ...
    def __len__(self) -> int: ...

    # Audio presets
    def create_preset(self, name: str, pool_dict: PoolDict) -> None: ...
    def delete_preset(self, name: str) -> None: ...
    def get_preset(self, name: str) -> Optional[PoolDict]: ...
    def list_presets(self) -> List[str]: ...

    # Video presets
    def create_video_preset(self, name: str, entry: Any, source_dur: float = 0.0) -> None: ...
    def delete_video_preset(self, name: str) -> None: ...
    def get_video_preset(self, name: str) -> Optional[VideoPreset]: ...
    def list_video_presets(self) -> List[str]: ...

    # Resolve
    def resolve_pool(self, pool: PoolDict) -> ResolvedPool: ...
    @staticmethod
    def _resolve_exclusive(pool: PoolDict, defaults: Any) -> ResolvedExclusive: ...

    # Entry / pool mutators
    def _normalize_entry(self, entry: Any) -> MarkerEntry: ...
    def _get_or_create_entry(self, marker_key: str) -> Any: ...
    def _ensure_pool(self, marker_key: str, pool_index: int) -> PoolDict: ...
    def _add_file_to_pool(self, marker_key: str, filename: str, pool_index: int = 0) -> None: ...
    def _remove_file_from_pool(self, marker_key: str, file_index: int, pool_index: int = 0) -> None: ...
    def _stamp_preset(self, marker_key: str, preset_name: str, pool_index: int = 0) -> None: ...
    def _detach_pool(self, marker_key: str, pool_index: int) -> bool: ...
    def _resolve_video_pools(self, entry: Any) -> List[VideoPoolDict]: ...

    # Sanitize / migration passes
    @staticmethod
    def _clean_pool_list(pools: List[PoolDict]) -> Tuple[List[PoolDict], int]: ...
    def _sanitize_video_presets(self) -> int: ...
    def _sanitize_video_pools(self) -> int: ...
    def _sanitize_video_pools_tracked(self) -> Set[str]: ...
    def _normalize_all(self) -> bool: ...
    def _migrate_legacy_exclusive(self) -> int: ...
    @staticmethod
    def _migrate_exclusive_pool(pool: Any) -> bool: ...
    @staticmethod
    def _migrate_colon_key(key: str) -> str: ...
    def _migrate_speed_mode_rename(self) -> None: ...
    def _migrate_video_timestamps_to_pools(self) -> Tuple[int, int]: ...

    # Persistence
    def reload_presets(self) -> None: ...
    def save_marker(self, key: str) -> None: ...
    def save_markers(self, keys: List[str]) -> None: ...
    def save_preset(self, name: str) -> None: ...
    def save_video_preset(self, name: str) -> None: ...
    def _db_save_marker(self, key: str) -> None: ...
    def _db_save_preset(self, name: str) -> None: ...
    def _db_save_video_preset(self, name: str) -> None: ...
    def _post_save(self, keys: Optional[List[str]] = None) -> None: ...
    def save_all(self) -> None: ...
    def delete_removed_files(
        self,
        old_marker_keys: Set[str],
        old_presets: Dict[str, Any],
        old_video_presets: Dict[str, Any],
        old_session_created: Set[Tuple[str, str]],
    ) -> None: ...
    def load_from_db(self) -> None: ...
