# Type stub for cue_lib.marker_store
from typing import Any, Callable, Dict, ItemsView, KeysView, List, Optional, Set, Tuple

from cue_lib._types import IgroupHookDict, MarkerEntry, PoolDict, VideoPoolDict, VideoPreset
from cue_lib.db import CueDatabase
from cue_lib.intensity import CueIntensityFlags, CueIntensityManager, CueIntensityResolution
from cue_lib.paths import CuePaths
from cue_lib.pool import CuePool
from cue_lib.preset_store import CuePresetStore
from cue_lib.state import CueContext

# =========================================================================
# Resolve snapshots
# =========================================================================

class ResolvedExclusive:
    """Resolved exclusive config snapshot. group 0 = Off."""

    group: int
    start: int
    hold: bool
    def __init__(self, group: int = 0, start: int = 0, hold: bool = False) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def __repr__(self) -> str: ...

class ResolvedPool:
    """Immutable pool snapshot after resolving presets."""

    refs: List[str]
    files: Optional[List[str]]
    volume: float
    frequency: int
    trigger_on_shake: bool
    exclusive: ResolvedExclusive
    igroup: Optional[IgroupHookDict]
    intensity: Optional[CueIntensityResolution]
    @property
    def volume_mult(self) -> Optional[float]: ...
    @property
    def freq_mult(self) -> Optional[float]: ...
    @property
    def level(self) -> Optional[int]: ...
    def __init__(
        self,
        refs: List[str],
        files: Optional[List[str]],
        volume: float,
        frequency: int,
        trigger_on_shake: bool,
        exclusive: Optional[ResolvedExclusive] = None,
        igroup: Optional[IgroupHookDict] = None,
        intensity: Optional[CueIntensityResolution] = None,
    ) -> None: ...
    def __repr__(self) -> str: ...

# =========================================================================
# CueMarkerStore
# =========================================================================

class CueMarkerStore:
    _db: Optional[CueDatabase]
    _paths: CuePaths
    _on_save: Optional[Callable[[], None]]
    _data: Dict[str, MarkerEntry]
    _preset_store: CuePresetStore
    _intensity: Optional[CueIntensityManager]

    # Transitional read-throughs to _preset_store (removed in the split's
    # final cleanup; consumers move to _cue.presets / _preset_store).
    @property
    def _presets(self) -> Dict[str, PoolDict]: ...
    @_presets.setter
    def _presets(self, value: Dict[str, PoolDict]) -> None: ...
    @property
    def _video_presets(self) -> Dict[str, VideoPreset]: ...
    @_video_presets.setter
    def _video_presets(self, value: Dict[str, VideoPreset]) -> None: ...
    @property
    def _session_created(self) -> Set[Tuple[str, str]]: ...
    @_session_created.setter
    def _session_created(self, value: Set[Tuple[str, str]]) -> None: ...
    def __init__(
        self,
        ctx: Optional[CueContext],
        db: Optional[CueDatabase],
        paths: CuePaths,
        on_save: Optional[Callable[[], None]] = None,
        preset_store: Optional[CuePresetStore] = None,
        intensity: Optional[CueIntensityManager] = None,
    ) -> None: ...

    # Dict-like surface
    def __getitem__(self, key: str) -> MarkerEntry: ...
    def __setitem__(self, key: str, value: MarkerEntry) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def get(self, key: str, default: Optional[MarkerEntry] = None) -> Optional[MarkerEntry]: ...
    def setdefault(self, key: str, default: MarkerEntry) -> MarkerEntry: ...
    def pop(self, key: str, *args: MarkerEntry) -> MarkerEntry: ...
    def items(self) -> ItemsView[str, MarkerEntry]: ...
    def keys(self) -> KeysView[str]: ...
    def __len__(self) -> int: ...

    # Audio presets
    def create_preset(self, name: str, pool_dict: PoolDict) -> None: ...
    def delete_preset(self, name: str) -> None: ...
    def get_preset(self, name: str) -> Optional[PoolDict]: ...
    def list_presets(self) -> List[str]: ...

    # Video presets
    def create_video_preset(self, name: str, entry: Any, source_dur: float = 0.0) -> None: ...
    def delete_video_preset(self, name: str) -> None: ...
    def get_video_preset(self, name: str) -> Optional[VideoPreset]: ...
    def list_video_presets(self) -> List[str]: ...

    # Resolve
    def resolve_pool(
        self,
        pool: PoolDict,
        speed: Optional[float] = None,
        variants: Optional[List[float]] = None,
        flags: Optional[CueIntensityFlags] = None,
        expand: bool = False,
    ) -> ResolvedPool: ...
    @staticmethod
    def _resolve_exclusive(pool: PoolDict, defaults: Any) -> ResolvedExclusive: ...

    # Entry / pool mutators
    def _normalize_entry(self, entry: Any, marker_key: str = "") -> MarkerEntry: ...
    def _get_or_create_entry(self, marker_key: str) -> Any: ...
    def _capture_filepath(self, entry: Any, marker_key: str) -> None: ...
    def _capture_speaker(self, entry: Any) -> None: ...
    def _ensure_pool(self, marker_key: str, pool_index: int) -> PoolDict: ...
    def _remove_file_from_pool(self, marker_key: str, file_index: int, pool_index: int = 0) -> bool: ...
    def _remove_ref_from_pool(self, marker_key: str, path: str, pool_index: int = 0, prune: bool = False) -> bool: ...
    def _clear_pool_files(self, marker_key: str, pool_index: int = 0) -> bool: ...
    def _stamp_preset(self, marker_key: str, preset_name: str, pool_index: int = 0) -> None: ...
    def _detach_pool(self, marker_key: str, pool_index: int) -> bool: ...
    def pool(self, marker_key: str, pool_index: int = 0) -> CuePool: ...
    def _resolve_video_pools(self, entry: Any) -> List[VideoPoolDict]: ...

    # Sanitize passes
    @staticmethod
    def _clean_pool_list(pools: List[PoolDict]) -> Tuple[List[PoolDict], int]: ...
    def _sanitize_video_presets(self) -> int: ...
    def _sanitize_video_pools(self) -> int: ...
    def _sanitize_video_pools_tracked(self) -> Set[str]: ...

    # Persistence
    def reload_presets(self) -> None: ...
    def save_marker(self, key: str) -> None: ...
    def save_markers(self, keys: List[str]) -> None: ...
    def _persist(self, key: str) -> None: ...
    def _save_marker(self, key: str) -> None: ...
    def _post_save(self, keys: Optional[List[str]] = None) -> None: ...
    def save_all(self) -> None: ...
    def delete_removed_files(self, old_marker_keys: Set[str]) -> None: ...
    def load_from_db(self) -> None: ...
