# Type stub for cue_lib.marker_context
from typing import Any, Dict, Final, List, Optional, Set, Tuple

# Module-level binding of the stdlib random module (import random as _random
# in the source). Declared as Any so tests can monkeypatch it.
_random: Any

# Exclusive-group tag shared by video marker pools. Defined in context.py with
# the contexts that stamp it.
CUE_EXCLUSIVE_GROUP: int

CUE_INTERVAL_SELECT_TOLERANCE: Final = 0.010
CUE_DUPLICATE_GAP_PX: Final = 28
CUE_TIMELINE_REF_W: Final = 480
CUE_DUPLICATE_GAP_FRAC: Final = 0.058333333333333334

from cue_lib._types import MarkerEntry, PoolDict, VideoPoolDict
from cue_lib.constants import CueLoopFrequency
from cue_lib.markers import CueMarkerManager


# =========================================================================
# Context classes
# =========================================================================

class CueMarkerContext:
    def __init__(self, manager: "CueMarkerManager") -> None: ...
    def add_file(self, file_index: int) -> None: ...
    def remove_file(self, pool_index: int, file_index: int) -> None: ...
    def clear(self) -> None: ...
    def add_pool(self) -> None: ...
    def remove_pool(self, pool_index: int) -> None: ...
    def get_active_index(self) -> int: ...
    def set_active_index(self, pool_index: int) -> None: ...
    def get_active_pool(self) -> PoolDict: ...
    def has_pools(self) -> bool: ...
    def set_exclusive(self, start: int, hold: bool) -> None: ...
    def toggle_exclusive(self) -> None: ...
    def apply_preset(self, preset_name: str) -> None: ...
    def add_folder(self, folder_path: str) -> None: ...
    def send_file(self, file_index: int, record: bool = True) -> None: ...
    def send_folder(self, folder_path: str, record: bool = True) -> None: ...
    def send_preset(self, preset_name: str, record: bool = True) -> None: ...

    # Internal (white-box tests exercise the pool helpers directly)
    _mgr: "CueMarkerManager"
    active_pool: int
    def _key(self) -> str: ...
    def _entry_and_pools(self) -> Tuple[Optional[MarkerEntry], List[Dict[str, Any]]]: ...
    def _sort_and_track(self, pools: List[Dict[str, Any]], tracked_entry: Dict[str, Any]) -> int: ...
    def _append_pool(self, entry: MarkerEntry, pools: List[Dict[str, Any]], pool_dict: Dict[str, Any]) -> None: ...
    def _record_use(self, kind: str, ref: str) -> None: ...

class CueImageContext(CueMarkerContext):
    def toggle_shake_trigger(self) -> None: ...

class CueDialogueContext(CueMarkerContext): ...

class CueVideoContext(CueMarkerContext):
    selected: Set[int]
    edit_text: str

    def __init__(self, manager: "CueMarkerManager") -> None: ...
    def add_file(self, file_index: int) -> None: ...
    def add_folder(self, folder_path: str) -> None: ...
    def add_pool(self) -> None: ...
    def add_interval_selection(self, pool_index: int) -> None: ...
    def apply_preset(self, preset_name: str) -> None: ...
    def apply_preset_active(self, preset_name: str) -> None: ...
    def send_preset(self, preset_name: str, record: bool = True) -> None: ...
    def clear(self) -> None: ...
    def clear_selection(self) -> None: ...
    def clear_selected_files(self) -> None: ...
    def commit_text(self) -> None: ...
    def duplicate_pool(self, ts_index: int) -> None: ...
    def delete_pool_ui(self) -> None: ...
    def finalize_drag(self) -> None: ...
    def set_selected_volume(self, value: float) -> None: ...
    def get_delete_message(self) -> str: ...
    def get_duration(self) -> float: ...
    def get_markers(self) -> List[VideoPoolDict]: ...
    def get_selected(self) -> Set[int]: ...
    def has_markers(self) -> bool: ...
    def nudge(self, delta: float) -> None: ...
    def remove_file(self, pool_index: int, file_index: int) -> None: ...
    def remove_pool(self, pool_index: int) -> None: ...
    def remove_selected(self) -> None: ...
    def select_tab(self, pool_index: int) -> None: ...
    def set_active_index(self, pool_index: int) -> None: ...
    def set_time(self, idx: int, new_time: float) -> None: ...
    def sync_text(self) -> None: ...

    # Internal: per-pool edit primitives shared by the single and multi paths
    # (multi just loops them over self.selected)
    def _shift_pool_time(self, pools: List[Dict[str, Any]], idx: int, delta: float) -> None: ...
    def _duplicate_gap(self) -> float: ...
    def _add_file(self, vid_key: str, filename: str, pool_index: int) -> None: ...
    def _remove_file(self, vid_key: str, path: str, pool_index: int) -> None: ...
    def _remove_path_from_selected(self, path: str) -> None: ...

class CueLoopContext(CueMarkerContext):
    def __init__(self, manager: "CueMarkerManager") -> None: ...
    def add_pool(self) -> None: ...
    def clear(self) -> None: ...
    def set_frequency(self, freq: int) -> None: ...

    @staticmethod
    def get_delay(frequency: int = CueLoopFrequency.MEDIUM) -> float: ...
