# Type stub for cue_lib.markers
from typing import Any, Dict, List, Optional, Set, Tuple

# Re-exported from their canonical homes: enum classes live in
# cue_lib.constants, the data layer + resolve snapshots in cue_lib.marker_store.
# Consumers (screens, trigger.py, tests) import them from cue_lib.markers.
# The `as X` form is pyright's explicit re-export -- plain imports from a stub
# are not re-exported when implicitReexport is off.
from cue_lib.constants import (
    CueExclusiveStart as CueExclusiveStart,
    CueLoopFrequency as CueLoopFrequency,
    CueContextType as CueContextType,
)
from cue_lib.marker_store import (
    CueMarkerStore as CueMarkerStore,
    ResolvedExclusive as ResolvedExclusive,
    ResolvedPool as ResolvedPool,
)

# All TypedDicts are defined in cue_lib._types (the single canonical source)
# and re-exported here for consumers that import from cue_lib.markers.
from cue_lib._types import (
    ClipboardData,
    MarkerEntry,
    PoolDict,
    VideoPoolDict,
    VideoPreset,
)

# Constructor-injected collaborators (wired in cue_z.rpy init -900, markers last).
from cue_lib.state import CueContext
from cue_lib.video.video import CueVideoManager
from cue_lib.audio.sfx_manager import CueSfxManager
from cue_lib.trigger import CueTriggerEngine
from cue_lib.video.video_editor import CueVideoEditor


# Bootstrap / coordinator functions.  They write to managers wired after
# CueMarkerManager (trigger, etc.), so they live at module level and read _cue.
def _cue_load_scalars_from_persistent() -> None: ...
def _cue_markers_send(kind: str, ref: object, record: bool = True) -> None: ...
def _cue_target_assign_tt() -> str: ...


# Context classes were split into cue_lib/marker_context.py; re-exported here
# so existing consumers can keep importing them from cue_lib.markers.
from cue_lib.marker_context import (
    CueImageContext as CueImageContext,
    CueDialogueContext as CueDialogueContext,
    CueVideoContext as CueVideoContext,
    CueLoopContext as CueLoopContext,
)


# =========================================================================
# CueMarkerManager
# =========================================================================

class CueMarkerManager:
    image: CueImageContext
    dialogue: CueDialogueContext
    video: CueVideoContext
    loop: CueLoopContext
    clipboard: Optional[ClipboardData]
    # SFX library [+] assign target; session-only, mutated by the fallback.
    target_context: str

    def __init__(
        self,
        ctx: CueContext,
        store: CueMarkerStore,
        vid_manager: CueVideoManager,
        sfx_manager: CueSfxManager,
        trigger: CueTriggerEngine,
        video_editor: CueVideoEditor) -> None: ...

    # SFX library target context ([+] assign target)
    def set_target_context(self, ctx_id: str) -> None: ...
    def target_is_available(self, ctx_id: str) -> bool: ...
    def resolve_target_context(self) -> str: ...
    def send_target(self, kind: str, ref: object, record: bool = True) -> None: ...
    def target_active_label(self) -> str: ...
    def get(self, key: str, default: Optional[MarkerEntry] = None) -> Optional[MarkerEntry]: ...
    def setdefault(self, key: str, default: MarkerEntry) -> MarkerEntry: ...
    def pop(self, key: str, *args: MarkerEntry) -> MarkerEntry: ...
    def items(self) -> List[Tuple[str, MarkerEntry]]: ...
    def keys(self) -> List[str]: ...

    def create_preset(self, name: str, pool_dict: PoolDict) -> None: ...
    def delete_preset(self, name: str) -> None: ...
    def reload_presets(self) -> None: ...
    def preset_remove_file(self, name: str, file_path: str) -> None: ...
    def get_preset(self, name: str) -> Optional[PoolDict]: ...
    def list_presets(self) -> List[str]: ...

    def create_video_preset(self, name: str, entry: MarkerEntry) -> None: ...
    def delete_video_preset(self, name: str) -> None: ...
    def get_video_preset(self, name: str) -> Optional[VideoPreset]: ...
    def list_video_presets(self) -> List[str]: ...
    def remove_video_preset_pool(self, name: str, pool_index: int) -> None: ...
    def remove_video_preset_pool_file(self, name: str, pool_index: int, file_path: str) -> None: ...
    def video_preset_out_of_range(self, name: str) -> int: ...
    def apply_video_preset(self, name: str) -> None: ...

    def resolve_pool(self, pool: PoolDict) -> ResolvedPool: ...

    def save_marker(self, key: str) -> None: ...
    def save_markers(self, keys: List[str]) -> None: ...
    def save_preset(self, name: str) -> None: ...
    def save_video_preset(self, name: str) -> None: ...
    def save_all(self) -> None: ...
    def delete_removed_files(
        self,
        old_marker_keys: Set[str],
        old_presets: Dict[str, Any],
        old_video_presets: Dict[str, Any],
        old_session_created: Set[Tuple[str, str]]) -> None: ...
    def load_persistent(self) -> None: ...
    # Post-restore reload callback, called by CueManualBackupManager (main thread).
    def _reload_after_restore(self, count: int) -> None: ...

    def copy_context(self) -> None: ...
    def paste_context(self) -> None: ...

    # Internal (accessed within cue_lib package)
    _store: CueMarkerStore
    _ctx: CueContext
    _vid_manager: CueVideoManager
    _sfx_manager: CueSfxManager
    _trigger: CueTriggerEngine
    _video_editor: CueVideoEditor

    @property
    def _data(self) -> Dict[str, MarkerEntry]: ...
    @_data.setter
    def _data(self, value: Dict[str, MarkerEntry]) -> None: ...
    @property
    def _presets(self) -> Dict[str, PoolDict]: ...
    @_presets.setter
    def _presets(self, value: Dict[str, PoolDict]) -> None: ...
    @property
    def _video_presets(self) -> Dict[str, VideoPreset]: ...
    @_video_presets.setter
    def _video_presets(self, value: Dict[str, VideoPreset]) -> None: ...
    @property
    def _session_created(self) -> Set[Tuple[str, str]]: ...
    @_session_created.setter
    def _session_created(self, value: Set[Tuple[str, str]]) -> None: ...

    def _get_or_create_entry(self, marker_key: str) -> MarkerEntry: ...
    def _ensure_pool(self, marker_key: str, pool_index: int) -> PoolDict: ...
    def _detach_pool(self, marker_key: str, pool_index: int) -> bool: ...
    def _resolve_video_pools(self, entry: Any) -> List[VideoPoolDict]: ...
    def detach_active_video_ts(self, *args: Any) -> None: ...
    def detach_pool_at(self, marker_key: str, pool_index: int) -> None: ...
    def _video_multi_file_edit(self, marker_key: str) -> bool: ...
