# Type stub for cue_lib.music
from typing import Any, Dict, List, Optional

class CueMusicManager:
    _is_installed: bool
    last_event: Optional[Dict[str, Any]]
    _original_music_play: Any
    _original_music_queue: Any
    _original_music_stop: Any
    _triggers: Dict[str, List[Dict[str, str]]]
    _pending: Optional[Dict[str, Any]]

    def __init__(self) -> None: ...
    def install(self) -> None: ...
    def reload(self) -> None: ...
    def triggers_for(self, replay_id: Optional[str]) -> List[Dict[str, str]]: ...
    def _current_scene_key(self) -> str: ...
    def capture_display(self) -> None: ...
    def _on_play(self, *args: Any, **kwargs: Any) -> Any: ...
    def _on_queue(self, *args: Any, **kwargs: Any) -> Any: ...
    def _on_stop(self, *args: Any, **kwargs: Any) -> Any: ...
    def _record(self, event_type: str, args: tuple, kwargs: dict, channel_offset: int) -> None: ...
    def _record_default_trigger(self, filenames: Any, in_replay: Any) -> None: ...
