# Type stub for cue_lib.paths
from typing import Final, Optional

CUE_MOD_DIRNAME: Final = "renpy_cue"
CUE_DIR_OVERRIDE_FILENAME: Final = "dir.txt"
CUE_BACKUP_DIR: Final = "backups"
CUE_BACKUP_AUTO_DIR: Final = "auto"

class CuePaths:
    _original_root: str
    _game_id: str
    _active_root: Optional[str]

    def __init__(self, root: str, game_id: str) -> None: ...
    @property
    def root(self) -> str: ...
    @property
    def original_root(self) -> str: ...
    @property
    def game_id(self) -> str: ...

    @property
    def in_game_base_dir(self) -> str: ...
    def icon(self, filename: str) -> str: ...

    @classmethod
    def platform_shared_dir(cls) -> str: ...
    @classmethod
    def resolve_root(cls) -> str: ...
    @classmethod
    def save_root(cls, path: str) -> None: ...
    @property
    def audio_dir(self) -> str: ...
    @property
    def music_dir(self) -> str: ...
    @property
    def marker_dir(self) -> str: ...
    @property
    def music_trigger_dir(self) -> str: ...
    def music_trigger_path(self, replay_id: str) -> str: ...
    @property
    def presets_dir(self) -> str: ...
    @property
    def audio_preset_dir(self) -> str: ...
    @property
    def music_preset_dir(self) -> str: ...
    @property
    def video_preset_dir(self) -> str: ...
    @property
    def video_dir(self) -> str: ...
    @property
    def shared_config_path(self) -> str: ...
    @property
    def backups_dir(self) -> str: ...
    @property
    def auto_backups_dir(self) -> str: ...
    @property
    def manual_backup_path(self) -> str: ...
