# Type stub for cue_lib.pool
from typing import Any, Optional

from cue_lib._types import PoolDict

class _CueFileContainer:
    _prunes: bool
    def _pool_dict(self) -> Optional[PoolDict]: ...
    def add_file(self, path: str) -> bool: ...
    def remove_file(self, path: str) -> bool: ...
    def clear_files(self) -> bool: ...
    def detach(self) -> bool: ...

class CuePool(_CueFileContainer):
    _prunes: bool
    def __init__(self, store: Any, marker_key: str, pool_index: int) -> None: ...
    def _pool_dict(self) -> Optional[PoolDict]: ...
    def detach(self) -> bool: ...
    def _ensure(self) -> PoolDict: ...
    def _prune(self) -> None: ...
    def _save(self) -> None: ...

class CueAudioPreset(_CueFileContainer):
    def __init__(self, store: Any, name: str) -> None: ...
    def _pool_dict(self) -> Optional[PoolDict]: ...
    def _ensure(self) -> None: ...
    def _save(self) -> None: ...

class CueVideoPresetPool(_CueFileContainer):
    def __init__(self, store: Any, name: str, pool_index: int) -> None: ...
    def _pool_dict(self) -> Optional[PoolDict]: ...
    def _ensure(self) -> None: ...
    def _save(self) -> None: ...

def _ops_for(pool_dict: Optional[PoolDict]) -> Any: ...
