# Type stub for cue_lib.preset_store
from typing import Any, Callable, Dict, List, Optional, Set, Tuple

from cue_lib._types import PoolDict, VideoPreset
from cue_lib.db import CueDatabase
from cue_lib.pool import CueAudioPreset, CueVideoPresetPool

# =========================================================================
# CuePresetStore
# =========================================================================

class CuePresetStore:
    _db: Optional[CueDatabase]
    _on_save: Optional[Callable[[], None]]
    _presets: Dict[str, PoolDict]
    _video_presets: Dict[str, VideoPreset]
    _session_created: Set[Tuple[str, str]]

    def __init__(self, db: Optional[CueDatabase], on_save: Optional[Callable[[], None]] = None) -> None: ...

    # Audio presets
    def create_preset(self, name: str, pool_dict: PoolDict) -> None: ...
    def delete_preset(self, name: str) -> None: ...
    def get_preset(self, name: str) -> Optional[PoolDict]: ...
    def list_presets(self) -> List[str]: ...
    def audio(self, name: str) -> CueAudioPreset: ...
    def preset_remove_file(self, name: str, file_path: str) -> None: ...

    # Video presets
    def create_video_preset(self, name: str, entry: Any, source_dur: float = 0.0) -> None: ...
    def delete_video_preset(self, name: str) -> None: ...
    def get_video_preset(self, name: str) -> Optional[VideoPreset]: ...
    def list_video_presets(self) -> List[str]: ...
    def video_pool(self, name: str, pool_index: int) -> CueVideoPresetPool: ...
    def remove_video_preset_pool(self, name: str, pool_index: int) -> None: ...
    def remove_video_preset_pool_file(self, name: str, pool_index: int, file_path: str) -> None: ...

    # Sanitize / migration passes
    def _sanitize_video_presets(self) -> int: ...
    def _migrate_preset_speed_mode_rename(self) -> None: ...
    def _migrate_video_presets_to_pools(self) -> int: ...
    def _migrate_preset_exclusive(self) -> int: ...

    # Persistence
    def reload_presets(self) -> None: ...
    def save_preset(self, name: str) -> None: ...
    def save_video_preset(self, name: str) -> None: ...
    def _db_save_preset(self, name: str) -> None: ...
    def _db_save_video_preset(self, name: str) -> None: ...
    def _post_save(self) -> None: ...
    def save_all(self) -> None: ...
    def delete_removed_files(
        self, old_presets: Dict[str, Any], old_video_presets: Dict[str, Any], old_session_created: Set[Tuple[str, str]]
    ) -> None: ...
    def load_from_db(self) -> None: ...
