from typing import Dict, List


class CueRecentManager(object):
    def __init__(self) -> None: ...
    def load(self) -> None: ...
    def touch(self, kind: str, value: str) -> None: ...
    def items(self) -> List[Dict[str, str]]: ...
