# Type stub for cue_lib.replays
from typing import Any, Dict, List, Optional, Set, Tuple

from cue_lib.marker_store import CueMarkerStore
from cue_lib.paths import CuePaths
from cue_lib.thumbs import CueThumbManager
from cue_lib.ui.components.select.select import CueSelect

def _cue_replay_labels(root: str, game_id: str) -> List[Tuple[str, int]]: ...
def _cue_replay_counts_from_store(markers: Dict[str, Any]) -> List[Tuple[str, int]]: ...
def _cue_speaker_label(who: Any) -> Any: ...
def _cue_speaker_display(tag: str) -> str: ...

CUE_MC_TAG: str

class CueReplayLibrary:
    def __init__(self, paths: CuePaths, marker_store: CueMarkerStore) -> None: ...
    def scan(self) -> None: ...
    def play(self, label: str) -> None: ...

    entries: List[Dict[str, Any]]
    pending_replay: Optional[str]
    cast: CueReplayCast
    cast_filter: CueCastFilter
    thumbs: CueThumbManager

class CueReplayCast:
    def __init__(self, paths: CuePaths) -> None: ...
    def record_speaker(self, replay_id: str, speaker: str) -> None: ...
    def cast_for(self, replay_id: str) -> Set[str]: ...
    def load_all(self) -> None: ...
    def all_speakers(self) -> List[str]: ...
    def _load(self, replay_id: str) -> Set[str]: ...
    def _save(self, replay_id: str, speakers: Set[str]) -> None: ...

    _paths: CuePaths
    _casts: Dict[str, Set[str]]

class CueCastFilter(CueSelect):
    def __init__(self, cast: CueReplayCast) -> None: ...
    def matches(self, replay_id: str) -> bool: ...
    def options(self) -> List[str]: ...
    def label(self, key: str) -> str: ...
    def chips_for(self, replay_id: str) -> List[str]: ...

    _cast: CueReplayCast
