# Type stub for cue_lib.runtime
from typing import Any, Optional, Tuple

def _cue_toggle_overlay() -> None: ...
def _cue_toggle_sfx_active() -> None: ...
def _cue_set_page(page: int) -> None: ...
def _cue_toggle_shake_trigger() -> None: ...
def _cue_show_overlay() -> None: ...
def _cue_full_reload() -> None: ...
def _cue_hide_overlay() -> None: ...
def _cue_sidebar_resize_dragged(drags: Any, event: str, x: int, y: int, st: float, at: float) -> None: ...
def _cue_refresh_context() -> None: ...
def _cue_log_context() -> None: ...
def _cue_get_top_layer() -> Tuple[Optional[str], Optional[str], Any]: ...
def _cue_refresh_channel(displayable: Any = None) -> None: ...
def _cue_tick_trigger() -> None: ...
def _cue_preview_music_preset(preset_name: str) -> None: ...
