# Type stub for cue_lib.settings

from typing import List

class CueSettings:
    setup_dir_text: str
    shared_dir_error: str
    shared_dir_success: str
    music_folders: List[str]
    sfx_folders: List[str]
    music_folder_drafts: List[str]
    sfx_folder_drafts: List[str]
    music_folder_errors: List[str]
    sfx_folder_errors: List[str]

    def __init__(self) -> None: ...
    def prepare_for_page(self) -> None: ...
    def confirm_shared_dir(self) -> None: ...
    def add_music_folder(self) -> None: ...
    def add_sfx_folder(self) -> None: ...
    def commit_music_folder(self, index: int) -> None: ...
    def commit_sfx_folder(self, index: int) -> None: ...
    def remove_music_folder(self, index: int) -> None: ...
    def remove_sfx_folder(self, index: int) -> None: ...

def _cue_apply_music_folders(folders: List[str]) -> None: ...
def _cue_apply_sfx_folders(folders: List[str]) -> None: ...
def _cue_refresh_loader_roots() -> None: ...
