# Type stub for cue_lib.speed
from typing import Any, Dict, List, Optional, Tuple
from renpy.display.video import Movie

class SpeedMode:
    SINGLE: str
    MULTI: str

class CueSpeedToast:
    toast_speeds: Optional[List[float]]
    toast_current: Optional[float]
    toast_tag: Optional[str]
    toast_timestamp: float
    toast_duration: float

    def __init__(self) -> None: ...
    def show(self, tag: str, duration: float = 4.1) -> None: ...
    def clear(self) -> None: ...

class CueVidSpeedSequence:
    active_tag: Optional[str]

    def __init__(self, resolver: CueVidSpeedResolver) -> None: ...
    def speeds_for(self, tag: str) -> Optional[List[float]]: ...
    def current_step_index(self) -> int: ...
    def speeds_grouped(self, tag: str) -> Optional[List[Tuple[float, int, int]]]: ...
    def contains(self, speed: float) -> bool: ...
    def append_speed(self, speed: float) -> None: ...
    def remove_at(self, index: int) -> None: ...
    def move(self, index: int, delta: int) -> None: ...
    def clear_sequence(self, tag: Optional[str] = None) -> None: ...
    def get_mode(self, tag: Optional[str] = None) -> str: ...
    def set_mode(self, mode: str, tag: Optional[str] = None) -> None: ...
    def paths_for(self, tag: str) -> Optional[List[str]]: ...
    def start(self, tag: str) -> None: ...
    def handle(self, tag: str) -> None: ...
    def cancel(self) -> None: ...
    def tick(self) -> None: ...

class CueVidSpeedResolver:
    paths: Dict[str, str]
    children: Dict[Any, Any]
    sequence: Optional[CueVidSpeedSequence]
    seamless_transition: bool

    def __init__(self) -> None: ...
    def speed_for(self, tag: str) -> float: ...
    def get_current_speed(self) -> float: ...
    def base_path_for(self, tag: str) -> Optional[str]: ...
    def cycle_speed(self, delta: int) -> None: ...
    def set_speed(self, speed: float) -> None: ...
    def toggle_seamless(self) -> None: ...
    def clear_pending(self) -> None: ...
    def invalidate(self, tag: str) -> None: ...
    def resolve(self, st: float, at: float, tag: str, base_path: str, orig_movie: Movie) -> Tuple[Any, Any]: ...
    def wrap_all_movies(self) -> None: ...
    def get_available_speeds(self, base_path: str) -> List[float]: ...
    def delete_variant(self, base_path: str, speed: float) -> None: ...
    def _get_speed_pref(self, tag: str) -> float: ...
    def _set_speed_pref(self, tag: str, speed: float) -> None: ...

    @staticmethod
    def preset_speeds() -> List[float]: ...
    @classmethod
    def variant_path(cls, base_path: str, speed: float) -> str: ...
    @classmethod
    def is_variant_of(cls, path: str, base_path: str) -> bool: ...
    @staticmethod
    def _split_ext(path: str) -> Tuple[str, str]: ...

# Module-level DynamicDisplayable callbacks
def _cue_resolver(st: float, at: float, tag: str, base_path: str, orig_movie: Movie) -> Tuple[Any, Any]: ...
def _cue_capture_kwargs(movie: Movie) -> Dict[str, Any]: ...

# Sequence popup actions
def _cue_seq_btn_hovered(index: int) -> None: ...
def _cue_seq_popup_dismiss() -> None: ...
def _cue_seq_delete() -> None: ...
def _cue_seq_move_left() -> None: ...
def _cue_seq_move_right() -> None: ...
