# Type stub for cue_lib.thumbs
from typing import Any, Dict, Optional

from cue_lib.paths import CuePaths

CUE_THUMBS_URL: str
CUE_THUMB_IMAGE_EXTS: tuple

def _cue_is_newer(remote: Optional[str], local: Optional[str]) -> bool: ...
def _cue_format_http_date(timestamp: Optional[float]) -> Optional[str]: ...

class CueThumbManager:
    def __init__(self, paths: CuePaths, fetcher: Any = None) -> None: ...
    def disable(self) -> None: ...
    def load(self) -> None: ...
    def maybe_download(self) -> None: ...
    def thumb_for(self, replay_id: str) -> Optional[str]: ...
    def _scan_marker_filepaths(self) -> Dict[str, str]: ...
    def _run(self) -> None: ...
    def _write_cache(self, tmp_path: str) -> None: ...

    _paths: CuePaths
    _dl: Any
    entries: Dict[str, str]
    _fallbacks: Optional[Dict[str, str]]
    state: str
    error: str
    _fetched: bool
    _disabled: bool
    _thread: Any
