# Type stub for cue_lib.undo
from typing import Optional

from cue_lib._types import UndoSnapshot
from cue_lib.marker_store import CueMarkerStore
from cue_lib.state import CueContext
from cue_lib.video.video_editor import CueVideoEditor
from cue_lib.markers import CueMarkerManager

class CueUndoManager:
    MAX_UNDO: int
    DEDUPE_WINDOW: float
    _previous: Optional[UndoSnapshot]
    _store: CueMarkerStore
    _ctx: CueContext
    _video_editor: CueVideoEditor
    _markers: Optional[CueMarkerManager]

    def __init__(
        self,
        store: CueMarkerStore,
        ctx: CueContext,
        video_editor: CueVideoEditor,
        markers: Optional[CueMarkerManager] = None) -> None: ...
    def seed(self) -> None: ...
    def reset(self) -> None: ...
    def capture(self) -> None: ...
    def can_undo(self) -> bool: ...
    def can_redo(self) -> bool: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def _snapshot(self) -> UndoSnapshot: ...
    def _restore(self, snap: UndoSnapshot) -> None: ...
    def _clamp_ui(self) -> None: ...
