# Type stub for cue_lib.undo
from typing import Optional

from cue_lib._types import UndoSnapshot

class CueUndoManager:
    MAX_UNDO: int
    DEDUPE_WINDOW: float
    _previous: Optional[UndoSnapshot]

    def __init__(self) -> None: ...
    def seed(self) -> None: ...
    def capture(self) -> None: ...
    def can_undo(self) -> bool: ...
    def can_redo(self) -> bool: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
