# Type stub for cue_lib.url_importer
from typing import Any, List, Optional, Tuple

CUE_URL_CONNECT_TIMEOUT: int
CUE_URL_CHUNK_SIZE: int
CUE_URL_MAX_REDIRECTS: int
CUE_URL_USER_AGENT: str

def _cue_find_cacert() -> Optional[str]: ...
def _cue_https_context() -> Any: ...

class _CueUrlError(Exception):
    pass

class _CueUrlCancel(Exception):
    pass

def _cue_is_private_ip(ip: str) -> bool: ...

class CueUrlImporter(object):
    url: str
    is_downloading: bool
    cancel_requested: bool
    download_done: int
    download_total: Optional[int]
    download_started: float
    download_label: str
    download_error: str
    download_status: str
    _thread: Any

    def __init__(self, importer: Any, fetcher: Any = None) -> None: ...
    def clear_status(self) -> None: ...
    def clear_url(self) -> None: ...
    def download_duration(self) -> float: ...
    def import_url(self) -> None: ...
    def cancel(self) -> None: ...
    def _check_url(self, url: str) -> Optional[str]: ...
    def _resolve_ips(self, host: str) -> List[str]: ...
    def _resolve(self, host: str) -> Any: ...
    def _open(self, url: str, timeout: float) -> Any: ...
    def _resolve_redirects(self, url: str) -> Tuple[str, Any]: ...
    def _write_body(self, resp: Any, tmp_path: str) -> None: ...
    def _worker(self, url: str) -> None: ...
    def _name_from_url(self, url: str) -> str: ...
    def _dedupe_name(self, imports_dir: str, name: str) -> str: ...
