# Type stub for cue_lib.util
from typing import Any, Callable, Dict, List, Optional, Set, Tuple, Union
from renpy.display.video import Movie

# Key helpers
def create_img_key(file: str) -> str: ...
def create_vid_key(file: str) -> str: ...
def create_loop_key(file: str) -> str: ...
def create_dlg_key(dlg_pair: Tuple[str, str]) -> str: ...
def is_img_key(key: str) -> bool: ...
def is_vid_key(key: str) -> bool: ...
def is_dlg_key(key: str) -> bool: ...
def is_loop_key(key: str) -> bool: ...
def _cue_strip_key_prefix(key: str) -> str: ...
def get_key_file(key: str) -> str: ...
def get_key_dialogue(key: str) -> str: ...
def get_key_prefix(key: str) -> str: ...

# Displayable helpers
def _cue_unwrap_displayable(name_or_displayable: Union[str, Any]) -> Any: ...
def _cue_atl_child_displayables(d: Any) -> Optional[List[Any]]: ...

# Persistent
def _to_str(obj: Any) -> Any: ...
def _cue_unwrap_persistent(data: Any) -> Any: ...

# Audio scan
def _cue_build_tree(flat_files: List[str]) -> List[Dict[str, Any]]: ...
def _cue_split_pipes(query: str) -> List[str]: ...
def _cue_compile_query(query: str) -> Callable[[str], bool]: ...
def _cue_filter_tree(tree: List[Dict[str, Any]], query: str) -> List[Dict[str, Any]]: ...
def _cue_query_matches(name: str, query: str) -> bool: ...
def _cue_matches_any(query: str, items: List[str]) -> bool: ...
def _cue_preset_search_matches(name: str, query: str) -> bool: ...
def _cue_igroup_search_matches(name: str, query: str) -> bool: ...
def _cue_filter_preset_files(name: str, query: str) -> List[str]: ...
def _cue_filter_igroup_folders(name: str, query: str) -> List[Dict[str, Any]]: ...

# Text escaping
def _cue_escape_text(s: Optional[str], brackets: bool = True) -> Optional[str]: ...

# Time formatting
def _cue_clamp_time(t: float, dur: float) -> float: ...
def _cue_format_time(seconds: Optional[float]) -> str: ...
def _cue_format_size(num_bytes: Optional[float]) -> str: ...
def _cue_format_duration(seconds: Optional[float]) -> str: ...
def _cue_speed_label(sp: float) -> str: ...
def _cue_parse_time(time_str: Optional[str]) -> Optional[float]: ...

# Debug logging
def _cue_log(msg: str) -> None: ...

# File resolution
def _cue_is_abs_path(path: str) -> bool: ...
def _cue_expand_folder_ref(
    files_list: List[str], folder_ref: str, disabled: Optional[Set[str]] = None
) -> List[str]: ...
def _cue_resolve_files(files: List[str]) -> List[str]: ...
def _cue_remove_ref(
    files: List[str], path: str, expand_fn: Optional[Callable[[List[str]], List[str]]] = None
) -> Tuple[List[str], bool]: ...
def _cue_clean_pool_list(pools: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], int]: ...
def _cue_migrate_exclusive_pool(pool: Dict[str, Any]) -> bool: ...
def _cue_pick_file(files: List[str], avoid_repeats: bool = True) -> Optional[str]: ...

# File system
def _cue_replace_file(src: str, dst: str) -> None: ...
def _cue_open_in_os_file_explorer(path: str) -> None: ...

# Screen helpers
def _cue_make_tab_action(fn: Callable[..., None], args_tuple: tuple, pi: int) -> Callable[..., None]: ...
def _cue_consume_return(fn: Callable[..., None], *args: Any) -> None: ...
def _cue_shift_held() -> bool: ...

# Displayable name helpers
def _cue_top_layer_name(name: Any) -> Optional[str]: ...
def _cue_top_movie_name(movie: Movie) -> Optional[str]: ...
def _cue_get_movie_play(movie: Movie) -> str: ...

# Transition helpers
def _cue_is_screenshake(trans: Any) -> bool: ...
def _cue_wrap_with_statement(original_with_statement: Any) -> Any: ...
def _cue_wrap_config_show(original_config_show: Any) -> Any: ...
def _cue_wrap_load() -> None: ...

# UI refresh decorator
def _cue_ui_refresh(fn: Callable[..., Any]) -> Callable[..., Any]: ...
