# Type stub for cue_lib.util
from typing import Any, Callable, Dict, List, Optional, Tuple, Union
from renpy.display.video import Movie

# Key helpers
def create_img_key(file: str) -> str: ...
def create_vid_key(file: str) -> str: ...
def create_loop_key(file: str) -> str: ...
def create_dlg_key(dlg_pair: Tuple[str, str]) -> str: ...
def is_img_key(key: str) -> bool: ...
def is_vid_key(key: str) -> bool: ...
def is_dlg_key(key: str) -> bool: ...
def is_loop_key(key: str) -> bool: ...
def _cue_strip_key_prefix(key: str) -> str: ...
def get_key_file(key: str) -> str: ...
def get_key_dialogue(key: str) -> str: ...
def get_key_prefix(key: str) -> str: ...

# Displayable helpers
def _cue_unwrap_displayable(name_or_displayable: Union[str, Any]) -> Any: ...
def _cue_get_movie_or_image(name_or_displayable: Union[str, Any]) -> Tuple[Any, Any]: ...
def _cue_atl_child_displayables(d: Any) -> Optional[List[Any]]: ...

# Persistent
def _to_str(obj: Any) -> Any: ...
def _cue_unwrap_persistent(data: Any) -> Any: ...

# Audio scan
def _cue_build_tree(flat_files: List[str]) -> List[Dict[str, Any]]: ...
def _cue_filter_tree(tree: List[Dict[str, Any]], query: str) -> List[Dict[str, Any]]: ...

# Time formatting
def _cue_clamp_time(t: float, dur: float) -> float: ...
def _cue_format_time(seconds: Optional[float]) -> str: ...
def _cue_speed_label(sp: float) -> str: ...
def _cue_parse_time(time_str: Optional[str]) -> Optional[float]: ...

# Debug logging
def _cue_log(msg: str) -> None: ...
def _cue_clear_debug_log() -> None: ...

# File resolution
def _cue_resolve_files(files: List[str]) -> List[str]: ...
def _cue_pick_file(files: List[str], avoid_repeats: bool = True) -> Optional[str]: ...

# File system
def _cue_replace_file(src: str, dst: str) -> None: ...

# Screen helpers
def _cue_make_tab_action(fn: Callable[..., None], args_tuple: tuple, pi: int) -> Callable[..., None]: ...
def _cue_shift_held() -> bool: ...

# Displayable name helpers
def _cue_top_layer_name(name: Any) -> Optional[str]: ...
def _cue_top_movie_name(movie: Movie) -> Optional[str]: ...
def _cue_get_movie_play(movie: Movie) -> str: ...

# Transition helpers
def _is_screenshake(trans: Any) -> bool: ...

# SFX playback helpers
def _cue_sfx_channel_name(index: int) -> str: ...
def _cue_sfx_channel_index(ch_name: str) -> int: ...
def _cue_loop_still_playing(channels: List[str]) -> bool: ...

# UI refresh decorator
def _cue_ui_refresh(fn: Callable[..., Any]) -> Callable[..., Any]: ...
