# Type stub for cue_lib.video
from typing import Final, Optional

CUE_SEEK_EPSILON: Final = 0.001

class CueVideoManager:
    channel: Optional[str]
    paused: bool
    refreshing: bool
    fps: int
    last_elapsed: float

    def __init__(self, channel: Optional[str] = None) -> None: ...
    def reset(self, channel: Optional[str] = None) -> None: ...
    def set_fps(self, fps: int) -> None: ...
    def reset_pause(self) -> None: ...
    def get_elapsed(self) -> float: ...
    def get_duration(self) -> float: ...
    def get_video_path(self) -> Optional[str]: ...
    def toggle_pause(self) -> None: ...
    def seek_to(self, target_time: float) -> None: ...
    def poll_autopause(self) -> None: ...
    def sync_paused(self) -> None: ...
    def time_label(self) -> str: ...
    def frame_label(self) -> str: ...
