# Type stub for cue_lib.video_editor
from typing import Any, Optional

CUE_VE_MODE_NORMAL: int
CUE_VE_MODE_INTERPOLATE: int
CUE_VE_MODE_FAST_PREVIEW: int

def _cue_esc(text: str) -> str: ...

class CueVideoEditorState:
    vpath: str
    factor_text: str
    last_error: str
    def __init__(self, vpath: str) -> None: ...

class CueVideoJob:
    job_id: int
    vpath: str
    fspath_in: str
    fspath_tmp: str
    factor: float
    encode_mode: int
    fspath_out: Optional[str]
    status: str
    progress: float
    error_msg: str
    start_time: float
    end_time: float
    total_frames: float
    passlog: Optional[str]
    cancelled: bool
    proc: Optional[Any]
    _resume_pass2: bool

    def __init__(self, job_id: int, vpath: str, fspath_in: str, fspath_tmp: str, factor: float, encode_mode: int, fspath_out: Optional[str] = None) -> None: ...
    def elapsed(self) -> float: ...
    def status_text(self) -> str: ...
    def filename(self) -> str: ...
    @property
    def speed_label(self) -> str: ...

class CueVideoEditQueue:
    def __init__(self, editor: "CueVideoEditor") -> None: ...
    @property
    def processing(self) -> bool: ...
    @property
    def current_job(self) -> Optional[CueVideoJob]: ...
    @property
    def jobs(self) -> list[CueVideoJob]: ...
    def enqueue(self, job: CueVideoJob) -> None: ...
    def poll(self) -> None: ...
    def retry(self, job_id: int) -> None: ...
    def cancel(self, job_id: int) -> None: ...
    def remove(self, job_id: int) -> None: ...
    def save_to_persistent(self) -> None: ...
    def load_from_persistent(self) -> None: ...
    def get_elapsed(self) -> float: ...
    def refresh_ui(self) -> None: ...

class CueVideoEditor:
    SPEED_MIN: float
    SPEED_MAX: float
    MODE_NORMAL: int
    MODE_INTERPOLATE: int
    MODE_FAST_PREVIEW: int

    active: bool
    encode_mode: int
    job_queue: CueVideoEditQueue

    def __init__(self) -> None: ...
    @property
    def processing(self) -> bool: ...
    @property
    def factor_text(self) -> str: ...
    @factor_text.setter
    def factor_text(self, value: str) -> None: ...
    @property
    def last_error(self) -> str: ...
    @last_error.setter
    def last_error(self, value: str) -> None: ...

    def check_prerequisites(self) -> tuple[str, str]: ...
    def extract_from_rpa(self) -> tuple[str, str]: ...
    def set_quick(self, mult: float) -> None: ...
    def commit_text(self) -> None: ...
    def nudge(self, delta: float) -> None: ...
    def open_editor(self) -> None: ...
    def close_editor(self) -> None: ...
    def get_factor(self) -> float: ...
    def set_encode_mode(self, mode: int) -> None: ...
    def prepare_create(self) -> None: ...
    def create(self, factor: float) -> None: ...
    def apply_variant(self, speed: float, out_fspath: str) -> None: ...
    def refresh(self) -> None: ...
    def refresh_ui(self) -> None: ...
