# Type stub for cue_lib.volume
from typing import Optional

from cue_lib._types import MarkerEntry

class CueVolumeManager:
    VOL_MIN: float
    VOL_DEFAULT: float
    VOL_MAX: float

    def __init__(self) -> None: ...
    def get(
        self,
        entry: Optional[MarkerEntry],
        trigger_key: Optional[str] = None,
        pool_index: Optional[int] = None) -> float: ...
    def write(self, trigger_key: str, new_vol: float, pool_index: Optional[int] = None) -> None: ...
    def adjust(self, trigger_key: str, delta: float, pool_index: Optional[int] = None) -> None: ...
    def get_master(self, trigger_key: str) -> float: ...
    def set_master(self, trigger_key: str, value: float) -> None: ...
    def adjust_master(self, trigger_key: str, delta: float) -> None: ...
    def get_effective(
        self,
        entry: Optional[MarkerEntry],
        trigger_key: Optional[str] = None,
        pool_index: Optional[int] = None) -> float: ...
    def adjust_video(self, delta: float) -> None: ...
