# Type stub for cue_lib.ui.components.select.select
from typing import Any, Final, List, Optional, Set, Tuple

CUE_SELECT_OPTION_H: Final = 18
CUE_SELECT_OPTION_GAP: Final = 1
CUE_SELECT_FRAME_PAD: Final = 8
CUE_SELECT_MAX_H: Final = 240

class CueSelect:
    def __init__(self) -> None: ...
    def toggle(self, key: Any) -> None: ...
    def clear(self) -> None: ...
    def selected_keys(self) -> List[Any]: ...
    def is_selected(self, key: Any) -> bool: ...
    def select(self, key: Any) -> None: ...
    def options(self) -> List[Any]: ...
    def label(self, key: Any) -> str: ...
    def is_open(self) -> bool: ...
    def toggle_open(self) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def trigger_rect(self) -> Optional[Tuple[int, int, int, int]]: ...
    def _content_h(self) -> int: ...
    def viewport_h(self) -> int: ...
    def frame_h(self) -> int: ...
    def rect(self) -> Optional[Tuple[int, int, int, int]]: ...
    def is_inside(self, x: float, y: float) -> bool: ...

    selected: Set[Any]
    _trigger_rect: Optional[Tuple[int, int, int, int]]
