# Type stub for cue_lib.sharing.exporter
from typing import Any, Dict, List, Set

class CueExportManager(object):
    scope: int
    file_types: int
    checked: Dict[int, bool]
    name: str
    author: str
    description: str
    contents_by_category: Dict[int, List[str]]
    counts: Dict[int, int]
    replays: List[dict]
    checked_replays: Set[str]
    current_replay: str
    export_status: str
    export_error: str
    is_exporting: bool
    export_fraction: float
    _export_thread: Any
    is_refreshing: bool
    _refresh_thread: Any

    @property
    def is_busy(self) -> bool: ...
    def __init__(self, paths: Any) -> None: ...
    def exports_dir(self) -> str: ...
    def refresh(self) -> None: ...
    def _kick_refresh_thread(self) -> None: ...
    def _refresh_worker(self) -> None: ...
    def _do_refresh(self) -> None: ...
    def _current_replay(self) -> str: ...
    def set_scope(self, scope: int) -> None: ...
    def set_file_types(self, file_types: int) -> None: ...
    def toggle_category(self, cat: int) -> None: ...
    def is_checked(self, cat: int) -> bool: ...
    def is_category_enabled(self, cat: int) -> bool: ...
    def any_unchecked(self) -> bool: ...
    def toggle_replay(self, label: str) -> None: ...
    def toggle_all_replays(self) -> None: ...
    def is_replay_checked(self, label: str) -> bool: ...
    def replay_labels(self) -> List[str]: ...
    def selected_contents(self) -> List[str]: ...
    def _category_contents(self) -> List[str]: ...
    def _replay_contents(self) -> List[str]: ...
    def clear_status(self) -> None: ...
    def export(self) -> None: ...
    def _build_zip_thread(
        self, contents: List[str], zip_path: str, name: str, author: str, description: str
    ) -> None: ...
    def _set_export_progress(self, written: int, total: int) -> None: ...
    def export_replay(self, label: str) -> None: ...
