# Type stub for cue_lib.sharing.url_importer
from typing import Any, Optional

from cue_lib.download import CueDownloader

class CueUrlImporter(object):
    url: str
    is_downloading: bool
    cancel_requested: bool
    download_done: int
    download_total: Optional[int]
    download_started: float
    download_label: str
    download_error: str
    download_status: str
    _thread: Any
    _dl: CueDownloader

    def __init__(self, importer: Any, fetcher: Any = None) -> None: ...
    def clear_status(self) -> None: ...
    def clear_url(self) -> None: ...
    def download_duration(self) -> float: ...
    def import_url(self) -> None: ...
    def cancel(self) -> None: ...
    def _write_body(self, resp: Any, tmp_path: str) -> None: ...
    def _worker(self, url: str) -> None: ...
    def _name_from_url(self, url: str) -> str: ...
    def _dedupe_name(self, imports_dir: str, name: str) -> str: ...
